### ISSUE TITLE
On web_timeline module when a new element is created, all other data dissapear from the view.

### ISSUE THREAD

**Issue by methodoos** [OCA/website#1009]
## Module
web_timeline

## Describe the bug
When a new element is created, all other data dissapear.
https://watch.screencastify.com/v/MNIkJF9C0jpfKVEdMabV

## To Reproduce
**Affected versions**: 14

Please see attached video

**Comment by pedrobaeza** [comment]
This doesn't belong here, but on OCA/web. And please try using `project_timeline` module that already adds the corresponding stuff on project.
