### ISSUE TITLE
Fixed dimensions are set on the table

### ISSUE THREAD

**Issue by brovalex** [OCA/website#1029]
## Module
Website editor

## Describe the bug
When editing the content of the table, a static value for the row height is added for some reason. This creates issue because as text is added to the table, it gets clipped at the fixed dimension. Clicking the "reset size" in the table option solves the issue, but it's not a desirable behaviour. 

## To Reproduce
**Affected versions**: tested on 16.3 enterprise

1. In web editor, add a text block
2. Add table to text block
3. Save the page
4. Edit the page
5. Add a row to the table
6. Save the page
7. Inspect the code, the new row has a height assigned e.g. `style="height:47px"`

**Expected behavior**
The is no reason to specify a fixed height on a table, td or tr unless the user explicitly asks for it.

**Comment by pedrobaeza** [comment]
This has nothing to do with any module of this repository. Please put the issue in Odoo itself.
