### ISSUE TITLE
[9.0] Moving modules from v8 OCA/website to v9 OCA/e-commerce

### ISSUE THREAD

**Issue by rafaelbn** [OCA/website#119]
Hi all,

This is an issue to discuss which modules we will move to OCA/e-commerce and which we won't

As discussed we must take this moment of moving to v9 to move modules to the correct repository.

All modules which depends from website_sale must be moved to OCA/e-commerce:
- website_event_register_free_with_sale
- website_sale_collapse_categories
- website_sale_order_company
- website_sale_unsaleable_options
- website_sale_vat_required

If you agree this 5 modules will go to https://github.com/OCA/e-commerce/tree/9.0

Thanks

**Comment by eLBati** [comment]
I agree

**Comment by pedrobaeza** [comment]
Please write this on the open issue about migration to 9.0

**Comment by rafaelbn** [comment]
Which is the open issue about migration to 9.0?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/website/issues/85

**Comment by rafaelbn** [comment]
Closing for make discussion in https://github.com/OCA/website/issues/85
