### ISSUE TITLE
website_blog_publication_date

### ISSUE THREAD

**Issue by max3903** [OCA/website#139]
This module adds a publication date field on a blog post to store the date when the post was published. This field is also used to sort public blog posts, instead of using the creation date.

**Comment by pedrobaeza** [comment]
I think https://github.com/OCA/website/tree/8.0/website_blog_mgmt makes something similar.

**Comment by lmignon** [comment]
@max3903 As mentioned by @pedrobaeza this functionality is provided by  https://github.com/OCA/website/tree/8.0/website_blog_mgmt

**Comment by max3903** [comment]
My bad! I am surprised by the name though. Thanks!
