### ISSUE TITLE
[website_cookie_notice] insecure content after click on cookie notice

### ISSUE THREAD

**Issue by andhit-r** [OCA/website#144]
Hi,

My odoo server runs behind nginx. All traffic redirect to https. With website_cookie_notice installed, after visitor click on cookie notice insecure content warning always shows. Tried to uninstall website_cookie_notice, no insecure content warning shows.

**Comment by lasley** [comment]
This is due to the link to http://www.allaboutcookies.org/ which does not provide an SSL version. This site is spammy anyways; I'll submit a PR to change the URI to Wikipedia or something instead

**Comment by pedrobaeza** [comment]
We follow the issue on the PR.
