### ISSUE TITLE
[8.0][website_legal_page] Xpath Expression breaks update and install !

### ISSUE THREAD

**Issue by michaelkarrer81** [OCA/website#150]
@pedrobaeza @rafaelbn The Xpath expressions 

``` XML
<template id="terms_of_use_link"
          inherit_id="website.layout_footer_copyright"
          name="Terms of use Link">
    <xpath expr="//footer//div/span[@t-field='res_company.name']" position="after">
        <span>- <a href="/page/terms">Terms of use</a></span>
    </xpath>
</template>
```

in 
- https://github.com/OCA/website/blob/8.0/website_legal_page/views/website_legal.xml#L9
- https://github.com/OCA/website/blob/8.0/website_legal_page/views/website_privacy.xml#L9
- https://github.com/OCA/website/blob/8.0/website_legal_page/views/website_terms.xml#L9

breaks installation or update of this addon since there is no footer element in the website.layout_footer_copyright view!

**Possible Fix**:

``` xml
<xpath expr="//span[@t-field='res_company.name']" position="after">
```

This expression is "sharp" enough in my opinion!

**Comment by pedrobaeza** [comment]
For me looks good, maybe:

``` xml
<xpath expr="//footer//span[@t-field='res_company.name']" position="after">
```

avoids problems when this field is in another part.

**Comment by rafaelbn** [comment]
@antespi please could you review this?

**Comment by michaelkarrer81** [comment]
``` xml
<xpath expr="//footer//span[@t-field='res_company.name']" position="after">
```

would still fail on my side. Only this works 

``` xml
<xpath expr="//span[@t-field='res_company.name']" position="after">
```

since there is no `<footer>...</footer>` tag in the inherited view.

**Comment by pedrobaeza** [comment]
@Yajo @antespi, can you check?

**Comment by yajo** [comment]
Enter any v8 website runbot and you will see the legal pages correctly added to the footer. This seems a local bug of your installation. Probably you changed manually or by any addon/theme `website.layout` or `website.layout_footer_copyright` views.

**Comment by michaelkarrer81** [comment]
@Yajo @pedrobaeza  @rafaelbn  Thank you for your answer but my installation is a stock oca 8.0 core with just this addon for testing?!? Really strange that it works on runbot flawlessly. Maybe there is a different Xpath processing since i am testing this on mac osx?

**Anyway:** If i look into the the view `website.layout_footer_copyright` you are inheriting from there is no footer tag at all:

``` XML
<template id="layout_footer_copyright" inherit_id="website.layout" name="Footer Copyright">
    <xpath expr="//footer" position="inside">
        <div class="container mt16 mb8">
            <div class="pull-right" t-ignore="true" t-if="not editable">
                Create a <a href="http://www.odoo.com/page/website-builder">free website</a> with
                <a class="label label-danger" href="http://www.odoo.com/page/website-builder">Odoo</a>
            </div>
            <div class="pull-left text-muted" itemscope="itemscope" itemtype="http://schema.org/Organization">
                Copyright &amp;copy; <span t-field="res_company.name" itemprop="name">Company name</span>
            </div>
        </div>
    </xpath>
</template>
```

Since this selector is making problems on, at least, one system, and it seems not really necessary **i kindly ask you to change it to `//span[@t-field='res_company.name']`.**

#### If anybody would have a good explanation why this fails it would be great:

It seems that on my side Xpath selectors will only work for exactly the inherited view and not the "calculated" xml of any inherited views before the inherited view. Is this the default behavior or should it first generate the full XML for all inherited views before the next inheriting view is parsed?!?

**Comment by yajo** [comment]
Yes, there is no `<footer>` tag, but you inherit from `website.layout`, which has it. Please post your logs. Also check the `website.layout` template and all its inherited ones, to see if they remove the footer in any point.

**Comment by michaelkarrer81** [comment]
@Yajo Thanks for your answer. I will post my logs but like i said i have stock OCA 8.0 so no other addons are involved. Also the `<footer>` tag is rendered in the website so it is there and not removed.

@Yajo @rafaelbn @dreispt Are you sure that all inherited views are always rendered before the "next" inheriting views Xpath expression is used? **Do you maybe know any other example in the odoo addons to proof this?** This is a really important question to answer for me since it is crucial for any xpath expression! Thanks for your help! 

In my tests i could always only target the XML of the inherited view and nothing more. 

Anyway since my change request is very small and would for sure not harm your addon at all it would be very nice if you could still consider to change your XPath expression?

**Comment by yajo** [comment]
As you can see, runbot works; that's enough proof to me.

The steps to fix a bug are:
1. Reproduce it.
2. Find the problem.
3. Fix it.

Let's stick to step 1 before going forward, or we might be fixing a bug where it is not.

**Comment by pedrobaeza** [comment]
Maybe it's a lxml problem, that acts different on MacOS...

**Comment by yajo** [comment]
That would be weird, don't you think? Python is cross-platform by nature.

**Comment by pedrobaeza** [comment]
But I don't find any other explanation...

**Comment by michaelkarrer81** [comment]
It is really something we should investigate on. 

Again it would be really helpful if someone could point out an example in the regular core where the XPATH expression does not directly belong to the inherited view but to the calculated XML! So we know this should be working by default.

If this is the case there should be "a lot of" XPath expressions that can be found - but right now i can not remember one.

**Comment by michaelkarrer81** [comment]
since i do have no time for additional investigations on that issue and it seems that i am the only one who hit this problem i close the issue.
