### ISSUE TITLE
[8.0][website_slide] Demo data error

### ISSUE THREAD

**Issue by andhit-r** [OCA/website#151]
My PR #149 got error on travis and runbot because one of the demo data raise an error

`File "/home/travis/build/OCA/website/website_slides/models/slides.py", line 434, in create
values['url']).get('values', dict())`
`File "/home/travis/build/OCA/website/website_slides/models/slides.py", line 581, in _parse_document_url
document_id, only_preview_fields)`
`File "/home/travis/build/OCA/website/website_slides/models/slides.py", line 595, in _parse_youtube_document
youtube_values = fetch_res['values'].get('items', list(dict()))[0]`
`ParseError: "list index out of range" while parsing /home/travis/build/OCA/website/website_slides/data/website_slides_demo.xml:76, near`
`<record id="slide_5" model="slide.slide">`
`<field name="name">OpenERP POS Indiegogo Campaign</field>`
`<field name="url">https://www.youtube.com/watch?v=C_Laaz4mORg</field>`
`<field name="channel_id" ref="channel_public"/>`
`<field name="category_id" ref="category_1"/>`
`<field name="website_published" eval="True"/>`
`<field name="tag_ids" eval="[(4, ref('tag3'))]"/>`
`</record>`

It maybe because the youtube link ( https://www.youtube.com/watch?v=C_Laaz4mORg ) already closed.

**Comment by pedrobaeza** [comment]
Are you sure the problem is that? Have you tried to put another link? If so, please make a PR changing this with something like for example https://www.youtube.com/watch?v=bncoCFGYucI

**Comment by andhit-r** [comment]
Yes @pedrobaeza . I have tried:
1. Create fresh DB with demo option. Failed on installation of website_slide
2. I change xml into valid Youtube URL. Success

Then I tried:
1. Create fresh DB without demo option
2. Install website_slide. Success.
3. Create a slide with youtube link https://www.youtube.com/watch?v=C_Laaz4mORg . No error message. But no respon on screen.
![website_slide_error](https://cloud.githubusercontent.com/assets/1947376/12614873/03710c70-c535-11e5-83d9-030d94b48b81.png)

When I looked into my log file. It shows same exception with travis log:

Traceback (most recent call last):
  File "/home/andhit_r/odoo8/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/andhit_r/odoo8/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/andhit_r/odoo8/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/andhit_r/odoo8/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/andhit_r/odoo8/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/andhit_r/odoo8/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/andhit_r/odoo8/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/andhit_r/odoo8/oca_website/website_slides/controllers/main.py", line 340, in dialog_preview
    data['url'], only_preview_fields=True)
  File "/home/andhit_r/odoo8/oca_website/website_slides/models/slides.py", line 581, in _parse_document_url
    document_id, only_preview_fields)
  File "/home/andhit_r/odoo8/oca_website/website_slides/models/slides.py", line 595, in _parse_youtube_document
    youtube_values = fetch_res['values'].get('items', list(dict()))[0]
IndexError: list index out of range

**Comment by pedrobaeza** [comment]
Thanks for the insights, but the way to test it is to install the bd with demo, but changing the url to one valid. Can you please try?

**Comment by andhit-r** [comment]
I have a create PR for this #152 . Travis passed but runbot failed. Trying to rebuild runbot now.

**Comment by andhit-r** [comment]
Closed with #152
