### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by david-vdv** [OCA/website#157]
After installation, I get the following error message above the web editor menu bar.
Could not get content for  website_snippet_marginless_gallery/static/src/css/website_snippet_marginless_gallery.css defined in bundle 'website.assets_frontend'

Any Idea how I can fix this?
The snippet seems to work but I don't get a dialog that asks for standard height of the images.

**Comment by pedrobaeza** [comment]
Restart the Odoo service and press reload your browser.

**Comment by david-vdv** [comment]
That did the trick, thanks for the quick response.
