### ISSUE TITLE
[8.0] [website_portal] Login redirection regression

### ISSUE THREAD

**Issue by LeartS** [OCA/website#164]
Commit https://github.com/OCA/website/commit/9141fe1b5166f32e10c87abdf120cebf5b190f1b introduced a regression. It absolutely should not redirect to `/` in every case, in particular it overrides redirects defined in the url, breaking for example login and signup from checkout page or every possible customization of the redirect from frontend modules/template modifications with the HTML editor.

**Comment by pedrobaeza** [comment]
cc @sergio-incaser

**Comment by LeartS** [comment]
Actually just noticed it was introduced in https://github.com/OCA/website/commit/5afd318fad7c2ddfb7e0fff096aac9a236d0f4cd cc @carlos-incaser

**Comment by sergio-teruel** [comment]
@LeartS @pedrobaeza Yes your are right, I'll fix it...
