### ISSUE TITLE
website_document_page

### ISSUE THREAD

**Issue by max3903** [OCA/website#19]
This module would allow you to manage and structure document pages on the website to be used for an online help or wiki. 

It would also allow you to provide a printable version with a table of content and subpages that you can use for a training course for example.

See also https://github.com/OCA/knowledge/issues/38

**Comment by sbidoul** [comment]
@max3903 how would/could this relate to the help_online module (https://github.com/OCA/web/tree/8.0/help_online) (or vice-versa)?

**Comment by max3903** [comment]
@sbidoul I have couple ideas in mind:
- an online help for the community (like Wikipedia) where anybody could contribute
- an export of the content into a module to install for a customer as internal documentation. Customer may want to keep it private (website is not installed) and update it to its needs. module_prototyper could be used for that.
- an export in a nice PDF with a TOC so a partner can use it to provide a standard training
