### ISSUE TITLE
Wrong contact us info

### ISSUE THREAD

**Issue by Whytehorse** [OCA/website#196]
The website uses the email of the "related user" for the HR employee who installed/created the website. Instead, it should use the company email specified in the company information.

Not really sure how else to explain it. The little blob that says "connect with us" has the correct data but when one goes to the page /page/website.contactus the contact info is not correct. It seems to be the contact info for a user who created the website.

**Comment by pedrobaeza** [comment]
The contact us form is from Odoo core, not from an OCA addon, so please put this issue on odoo/odoo.
