### ISSUE TITLE
website_logo: original company logo is unnecessarly converted to a square image which leads to ugly reports

### ISSUE THREAD

**Issue by treviser** [OCA/website#199]
When I install website_logo, the image size of the original company_logo is changed to a square image and the logo is vertically centered. Example: I have a logo with a relationship of width 2 units and height 1 unit. The module creates a square company logo (width 2 units, height 2 units) where my original logo is vertically centered. Without installing the module, my company logo keeps the original relationship between width and height.
The result is:
- the company logo needs to much space in the backend left navigation pane
- for the reports the company logo is automatically downsized again and the resulting logo on the reports is to small.

Is there anything I can do about it?

**Comment by treviser** [comment]
@lasley Do you have any idea why that happens?

**Comment by lasley** [comment]
Hi @treviser 

I don't see how this module could be touching your logo; we're not even importing any of the image translation tools. It seems to work just fine on my local as well.

Just to make sure I'm understanding correctly, your logo is transformed to a square immediately after installing this module? The change is immediately noticeable on the left nav bar?

**Comment by treviser** [comment]
It is very strange, I have to further investigate the issue. It does work without the module for logos which have not been used before while the module was installed. But if I do uninstall the module and try to use the same logo which was uploaded once with the module installed (even if I upload it again) it is squared.

**Comment by treviser** [comment]
I have found out the issue: When a logo has a width of more than 1024 pixel, it will be converted to a square by Odoo core.
