### ISSUE TITLE
website_integrator for odoo-community.org

### ISSUE THREAD

**Issue by max3903** [OCA/website#209]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=38333027)](https://www.bountysource.com/issues/38333027-website_integrator?utm_source=38333027&utm_medium=shield&utm_campaign=ISSUE_BADGE)

The OCA is using website_partner to display the list of OCA sponsors on http://www.odoo-community.org. 

We would like to display a second list for integrators. The partner page can be the same as the website_partner but the menu item is different and there would be a field on the partner to set the integrator level.

**Comment by ManishS-OpusVL** [comment]
Hi Maxime,

There is one module called **_'website_crm_partner_assign'._** which could be useful for this requirement. This module allows creating different Grades like Resellers, Integrators, Sponsors, etc as per requirement and mapping that with required partners present in Odoo db and which can be further published on to the desired web page.

A screenshot of sample page I created while testing this module is provided here in attachment, for your reference.

Regards,
Manish
![oca integrator page](https://cloud.githubusercontent.com/assets/18611783/16005628/24e3400c-3160-11e6-806e-b93b83532417.png)

**Comment by ManishS-OpusVL** [comment]
Hi Maxime,

Adding further to my comment, here are the steps details to be followed after installation of this module **_''website_crm_partner_assign''._**

**1) Create a new Partner Grade say, 'Integrators' using below steps.**
     - Go to Sales -> Configuration -> Leads & Opportunities -> Partner grade. 
     - Click  on 'Create' button
     - Enter Grade name as 'Integrators' and make sure 'Published on Website' checkbox is ticked.
     - Click on 'Save' button

**2) Mapping of 'Integrator' Grade with Partners.**
    For displaying the partners in the Integrators list on website, a mapping of the partner grade created in above step 1 needs to be done with the partners present in Odoo database. 
    Follow steps below:
    - Go to 'Sales -> Customers' and open the required partner form.
    - In the 'Geo Localisation' tab, select the Grade 'Integrator' from dropdown, created in above    step  1.
    -  In the 'Sales & Purchase' tab, make sure 'Publish' checkbox is ticked. 
    - Save the record.

 **3) Adding the Integrators list created in above steps, on the webpage**
    - Go to Website module & create a new web page, say 'Odoo Integrators'
    - Obtain the link of 'Resellers' present in footer section in 'Connect with us'.
    - Go to 'Edit Menu' & append this Reseller link with the new web page created, 'Odoo Integrators'.

This should get you running with your requirement. Please do let me know in case of any more query.

Thanks !

Kind regards,
Manish

**Comment by max3903** [comment]
@ManishS-OpusVL Sorry for the confusion. This is what we are currently using for the sponsorship level.

**Comment by ManishS-OpusVL** [comment]
Hi Maxime,

I have found a new module called **_'website_customer'_** which can be used for Integrators page  alongwith the existing module _**'website_partner/website_crm_partner_assign'.**_ for Sponsors page.

I have tested by installing both these modules and were able to produce both 'Sponsors' & 'Integrators' page simultaneously without any conflict.

I have enclosed here the screenshot of my working for your reference. Also can provide you the instructional steps, if needed.

Regards,
Manish
![integrator page](https://cloud.githubusercontent.com/assets/18611783/16109526/3648660e-33a1-11e6-94db-07820b575b16.png)

![sponsors page](https://cloud.githubusercontent.com/assets/18611783/16109511/21937aaa-33a1-11e6-9b57-7ac679e2c5df.png)

**Comment by elicoidal** [comment]
:+1:

**Comment by max3903** [comment]
@ManishS-OpusVL We planned to use website_customer to display references.
@OCA/board Shall we change the plan? So far I haven't received any content for that section.

**Comment by nhomar** [comment]
I am not agree of display this page sorry.

It is an unfear competition directly with partner program on odoo.

At least we define first the rules to be promoted here.

The main reason here from my PoV is that it does not add any value different from the fact of build a network of unfear competition.

But may be I do not know the hole vision.

**Comment by max3903** [comment]
@nhomar Odoo Partner Program is only based on revenues from Odoo Enterprise.

The integrator page aims to provide a better portrait/history of an integrator within the Odoo ecosystem with:
- his Odoo Partnership level
- his OCA Sponsorship level
- his references
- his employees
- their contributions based on the Github statistics from @legalsylvain module
- their membership history and status
- their responsibility within the OCA: OCA representative, PSC Members, etc.

**Comment by dreispt** [comment]
@max3903 I experimented to add a BountySource badge to the issue description.

**Comment by dreispt** [comment]
@max3903 We should have a `has_bounty` Label, but I can't create it.
