### ISSUE TITLE
Runbot Redirect for Website 9.0 branch yields 404

### ISSUE THREAD

**Issue by lasley** [OCA/website#218]
If you try to use the ReadMe Runbot URI for v9 branch of website, you will get a 404 error:

404 - https://runbot.odoo-community.org/runbot/186/9.0
200 - https://runbot.odoo-community.org/runbot/186/8.0

**Comment by Garamotte** [comment]
Already discussed here : https://github.com/OCA/knowledge/issues/86

**Comment by pedrobaeza** [comment]
I close this one to continue in the other issue.
