### ISSUE TITLE
[8.0][website_slide] 403: Forbidden

### ISSUE THREAD

**Issue by collex100** [OCA/website#220]
On the demo page:
http://3150062-8-0-2e960e.runbot2.odoo-community.org/slides
there is a warning
403: Forbidden
When I installed I got the same warning.
Please tell me how to fix it? Thank you!

**Comment by rafaelbn** [comment]
Please @collex100 open the issue following the link provided in the module:

https://github.com/OCA/website/issues/new?body=module:%20website_slides%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**

Thanks!
