### ISSUE TITLE
Coveralls not reporting to PRs

### ISSUE THREAD

**Issue by lasley** [OCA/website#247]
Coveralls are running via the `travis_after_tests_success`, but not reporting back to PRs for success/fail.

Example is #217 and the relevant Coveralls - https://coveralls.io/builds/7691307

IIRC this is supposed to be an automated thing, so not sure what's up. Figured it was worth an issue for tracking.

**Comment by pedrobaeza** [comment]
Maybe the problem is the indentation of this line: https://github.com/OCA/website/blob/ed81d5b49507841599d4d11357b62079f096c0fb/.travis.yml#L38

**Comment by lasley** [comment]
@pedrobaeza - the YML still parses though, so I don't think that's it. I tried to test this [using a PR in the LasLabs repo](https://github.com/laslabs/website/pull/1), and Coveralls is working fine. This leads me to believe that the notification settings in the Coveralls project have been edited for some reason.

**Comment by pedrobaeza** [comment]
I have just checked and it's not that:

![seleccion_001](https://cloud.githubusercontent.com/assets/7165771/18148809/6559dac8-6fdc-11e6-8381-e83da7d20298.png)

We have to assume that coveralls fails sometimes. There's a proposal to replace it with Codecov: https://github.com/OCA/maintainer-quality-tools/pull/342

I'm going to enable it to have the double check.

**Comment by pedrobaeza** [comment]
Please rebase and see what happens

**Comment by lasley** [comment]
I crossed some Git wires accidentally instead of a simple rebase, but desired effect of triggering a new build was achieved. No go on the coverage still 😦

**Comment by pedrobaeza** [comment]
Sorry, I also crossed PRs and didn't merge the required one. Try again now.

**Comment by lasley** [comment]
Closing - Codecov is amazing, Coveralls smells
