### ISSUE TITLE
[8.0] website_legal_page xpath with "." in attribute value will not work with lxml 3.3.5

### ISSUE THREAD

**Issue by michaelkarrer81** [OCA/website#261]
It seems that lxml on mac and some linux distributions will not work with "." dots in attribute values which will prevent website_legal_page from installing.

`AttributeError: Element '<xpath expr="//footer//div/span[@t-field='res_company.name']">'``

Any clue why on some platforms "." is not a valid character in xpath attribute values?

lxml version is 3.3.5 (but will still fails with 3.6.4 on MacOSX)

**Comment by pedrobaeza** [comment]
But I don't see any `.` in that xpath...

**Comment by michaelkarrer81** [comment]
It's in the value of the attribute @t-field `res_company.name` 

"res_company" is separated from "name" with a dot.

This also happened when i tried my own xpath selectors with a "." in an attribute value so it seems this might be a more generic problem.

If i change the selector to  `<xpath expr="//footer//div/span">` it works. Even if the selector is much "worse" now.

Since i guess the installation of this addon works for a lot of odoo users this might be an OS, python-version or lxml specific problem but since i used exactly the versions of all libs from requirements.txt and also tried with newer versions of python and lxml with no success i am out of ideas.

**Comment by pedrobaeza** [comment]
Wow, it's in that part!! I can't believe it. I can imagine the problem, but we can't workaround this I'm afraid.

**Comment by michaelkarrer81** [comment]
Would you point me in the direction where you think the error results from?

Because with more website qweb templates xpath selectors like this will be more and more common. If this prevents odoo (or at least some addons) to install on certain platforms we shoudl either fix this or avoid dots in attribute values at all.

I tried other workarounds like escaping the dot or using xpath functions like concatenate to build the string but with no success so far.

**Comment by pedrobaeza** [comment]
I'm afraid I don't have any clue. What you can do is to mount an example in pure Python and report to the lxml project.

**Comment by michaelkarrer81** [comment]
I found a way that would work:

`<xpath expr="//footer//span[contains(@t-field, 'res_company.name')]" position="after">`

**Comment by pedrobaeza** [comment]
Well, we can switch then to that form, but as it's not the usual one, we can expect another modules that appears using the other technique. You are too lonely in the Mac world...

**Comment by michaelkarrer81** [comment]
Would be really great if at least in the OCA addons we could use this "works everywhere" format of such xpath selectors.

Would you accept a merge request if i change this in website_legal_page?

I am not convinced that this is MacOS related. I guess it's some Python package or a real odoo bug. Since i do not know enough about the internals of odoo and how they parse the xpath selectors i am not able to investigate further. Would be a real benefit if some framework expert could take a look on this.
