### ISSUE TITLE
[8.0] website_event_register_free - Register public user without event seats_max

### ISSUE THREAD

**Issue by angelmoya** [OCA/website#263]
After install website_event_register_free:
- Create event without event seats_max, set only name and dates (minimun data), and do public to be available on website
- Without login on website (with public user) go to event, set quantity of tickets and click on register now.
- As you are not logged, you must to set data (name, company, email, telephone), but quantity selector is not shown 

I'm working on a PR to solve

**Comment by pedrobaeza** [comment]
Closing as there's a PR
