### ISSUE TITLE
website_event_register_free_with_sale: Error 500 when buying a Event with price

### ISSUE THREAD

**Issue by rafaelbn** [OCA/website#27]
1 - 
![20-04-2015 14-18-56](https://cloud.githubusercontent.com/assets/8736623/7229857/a9ab4dcc-e768-11e4-8351-e25556e5ae7a.png)
2 - 
![20-04-2015 14-20-24](https://cloud.githubusercontent.com/assets/8736623/7229862/b0bf54a0-e768-11e4-939d-9acf53b96e09.png)
3 - 
![20-04-2015 14-20-40](https://cloud.githubusercontent.com/assets/8736623/7229867/b70f9ac2-e768-11e4-94d8-d0bc3ffe3236.png)
4 - Log:
File "/var/openerp/project/website_event_register_free_with_sale/controllers/website_sale.py", line 56, in checkout
return super(WebsiteSale, self).checkout(self, *_post)
File "/var/openerp/common/openerp/v8/openerp/http.py", line 399, in response_wrap
response = f(_args, **kw)
TypeError: checkout() takes exactly 1 argument (2 given)

**Comment by pedrobaeza** [comment]
It seems you don't have last version, because the line miss one `*`:

https://github.com/OCA/website/blob/8.0/website_event_register_free_with_sale/controllers/website_sale.py#L56

**Comment by rafaelbn** [comment]
@JavierIniesta could you check this please?
