### ISSUE TITLE
[TRANSIFEX] Is the synchronization working?

### ISSUE THREAD

**Issue by sebalix** [OCA/website#285]
Hi,

I'm quite new to Transifex, and I was looking for information about the synchronization, I read somewhere (didn't remember...) that the Transifex sync was done once a week by a bot.
I made some translations one month ago (website_cookie_notice on branch 9.0, FR translations), but they are not merged yet. Is there a validation process? Or maybe I forgot something on Transifex... ?

Regards,

**Comment by yajo** [comment]
It's failing ATM.

**Comment by pedrobaeza** [comment]
With this improvement https://github.com/OCA/maintainer-tools/pull/244 (already working in our bot) should be fixed.

**Comment by sebalix** [comment]
Great, thank you @pedrobaeza , I confirm that the translations have been updated.
