### ISSUE TITLE
[9.0]  website_logo does not load the logo

### ISSUE THREAD

**Issue by StephanRozendaal** [OCA/website#289]
website_logo does not load the logo.

In the code it tries to find a logo where the domain is equal to a name of a website ([see](https://github.com/OCA/website/blob/9.0/website_logo/controllers/main.py#L39)).
Is this as intended?

Shouldn't it be:
Take the logo where the domain is equal to the domain that is set on the website model.

**Comment by lucode** [comment]
I would be happy if this could be fixed. 
Note: Read me is not related to Version 9 where the logo sites in Website Admin menu.

**Comment by StephanRozendaal** [comment]
I would be happy to fix it! And I'll also take a look at the read me and bring it up to date.

**Comment by lucode** [comment]
I just recognized that the module works fine if you have a one database system. When I use dbfilter=^%h$ it does not work with more then one database. Webserver is nginx.

**Comment by lucode** [comment]
Hi Stephan, sorry but I experience the same issue after installing your fixed version.

**Comment by StephanRozendaal** [comment]
@lucode Can you give me more details about your set-up?

What my fix included is that it matches the host value of the HTTP header of the incoming request to the domain field of an Odoo website.

Can you check the following:
 - Is the domain field set on the website in Odoo (It's somewhere in the website admin module)
 - Did you configure nginx so it preserves the host header of the incoming request?

**Comment by pedrobaeza** [comment]
As no answer, I close the issue.

**Comment by lucode** [comment]
Sorry for the late answer @StephanRozendaal did miss your reply:
I can't find a domain field in website admin only the Website Name. But the system parameter web.base.url is set correct. I us nginx with the following configuration related to host header:
```
## http redirects to https ##
server {
    listen 80;

    server_name *.demo.koina.eu;

    # Strict Transport Security
    add_header Strict-Transport-Security max-age=2592000;
    rewrite ^/.*$ https://$host$request_uri? permanent;

    return 301 https://$server_name$request_uri;
	}
```

```
 ## https site##
server {
    listen 443 ssl http2;

    server_name *.demo.koina.eu;

    root        /usr/share/nginx/html;
    index       index.html index.htm;

............
    add_header Strict-Transport-Security max-age=15768000;
```

**Comment by StephanRozendaal** [comment]
@lucode: The domain in website admin is hidden beneath a pop-up triggered by a button at the top of the website form. It's the button next to the drop-down of all the websites that are in the system.
