### ISSUE TITLE
[9.0] website_snippet_anchor is blocking menu

### ISSUE THREAD

**Issue by lucode** [OCA/website#304]
This module is blocking the editing of the menu from frontend and backend.
see the forum post:
https://www.odoo.com/de_DE/forum/hilfe-1/question/v9-website-menu-is-blocked-for-editing-111990

**Comment by pedrobaeza** [comment]
Please try on runbot to see if you reproduce the problem.

**Comment by rafaelbn** [comment]
Please @lucode try here http://3275938-9-0-3c6c72.runbot1.odoo-community.org/?db=3275938-9-0-3c6c72-all (admin/admin) and let us know if you can reproduce problem. Thanks

**Comment by lucode** [comment]
It does reproduce the error in runbot. No editing of Menu entries possible.

**Comment by pedrobaeza** [comment]
@Yajo, can you check?

**Comment by yajo** [comment]
Right now I see this problem in main 9.0 branch build:

![captura de pantalla de 2017-01-05 12-58-18](https://cloud.githubusercontent.com/assets/973709/21679884/b06475f0-d346-11e6-8ed4-c579c174d9ef.png)

I know it from other times, let me add a couple of quick fixes and see if it works.
