### ISSUE TITLE
[8.0] website seo redirection original URL is not available any longer after new entry

### ISSUE THREAD

**Issue by winston6071** [OCA/website#313]
create a new Entry 
example: 
original URL:
http://www.yourdomain.com/shop/product/testproduct-6
destination URL:
http://www.yourdomain.com/specials/testproduct-6
relocate "enabled"

The docu states that if this is set as described both links should work but run always into the destination URL..... 
I was 100% sure that this already worked... 
but now it does not anymore if i exactly do this above example the original url is not avilable anymore. and i get 500 internal server error.

**Comment by pedrobaeza** [comment]
You shouldn't do redirections with special URLs that are handled by controllers. Only on static pages.
