### ISSUE TITLE
website_analytics_piwik issue

### ISSUE THREAD

**Issue by alanljj** [OCA/website#32]
my piwik plugin install and configured very smoothly without any error. and Piwik start tracking visitors information. But when we click "send by email" on Quotation or Purchase module found following error:

QWebException: "'NoneType' object has no attribute 'piwik_analytics_host'" while evaluating
'website.piwik_analytics_host'

**Comment by hbrunn** [comment]
@alanljj #33 should fix this

**Comment by alanljj** [comment]
Thanks! after update file: website/website_analytics_piwik/views/templates.xml, the problems was solved.

May I ask why don't merger this to the master? so people can get the latest repository when git clone it.
