### ISSUE TITLE
notification settings and digest mail notification

### ISSUE THREAD

**Issue by simahawk** [OCA/website#320]
A customer needs digest notifications (weekly, daily, etc) on some website contents.
I wonder if there's already something there for:

* managing settings/subscriptions (a specific panel in user's home)
* a mailing list digest option
* any other goodie related to this subject :)

Any pointer? Any must-have? Any "I've done that, it's here[link]"? :smile:

**Comment by pedrobaeza** [comment]
You can look in https://github.com/OCA/social/tree/9.0/mass_mailing_custom_unsubscribe for a certain automation on the first point when unsubscribing from the mail link and using mass mailing lists.

**Comment by simahawk** [comment]
hmm maybe I'm wrong but I don't see any automation there, is just a way for customizing unsubscribe link in mass mailing.
I'll try to explain better what I want to achieve, maybe in a social PR.
