### ISSUE TITLE
[RFC] website_blog_permalink: Canonical Blog URIs

### ISSUE THREAD

**Issue by lasley** [OCA/website#330]
This module will allow for the configuration of canonical blog URIs, similar to the way that Wordpress does. 

It will leverage [`website_seo_redirection`](https://github.com/OCA/website/pull/329) to redirect the pages. An option will be provided for the permalinks to either move the page or simply redirect. The default will be to move the page (`website.seo.redirection.relocate_controller = True`)

It will allow the following options for URI schemas:
* Slug (default) - `/blog/{{ slug }}`
* Day & Slug - `/blog/{{ year }}/{{ month }}/{{ day }}/{{ slug }}`
* Month & Slug - `/blog/{{ year }}/{{ month }}/{{ slug }}`
* Year & Slug - `/blog/{{ year }}/{{ slug }}`
* Custom - string

The custom structure will allow for string interpolation, providing the following variables:
* year
* month
* day
* slug

Does anyone know of any pre-existing code or strategy we can base on for this?

**Comment by pedrobaeza** [comment]
Good idea, but no, I don't know anything in this matter.

**Comment by simahawk** [comment]
@lasley nice thing to have. I won't limit it just to blogs tough. This is the typical use case but you could benefit from this base feature in several situations (events, just to name one). 
I'm not aware on any implementation in odoo ecosystem.
