### ISSUE TITLE
Website SEO redirection improvements

### ISSUE THREAD

**Issue by rruebner** [OCA/website#337]
Hi @lasley @Yajo,

The module website_seo_redirection is a really nice and simple solution for customising any url in odoo. But I think to manage all urls manually can be a hard. Currently the migration from odoo 9 to 10 (#329) is in progress, so after the migration is done I want to provide some improvements.

But before creating a PR I want to discuss if the improvements are really needed (to be honest it was not my idea, I saw this approach in another [github repo](https://github.com/treytux/odoo-website/tree/master/website_url_friendly).

I want to add two new fields to the website.seo.redirection model, res_model and res_id. These fields are not required and should be used by other modules which extends / simplify the handling for url customisation for specific cases (like it was done in the linked github repo).

For the start I would add two new modules which simplifies the url customisation for products (website_seo_redirection_product) and blog posts (website_seo_redirection_blog). The goal for these additional modules is to add a new field seo_url to models like product.template, product.public.category, blog.post etc. in the backend and link it to their related redirection url in website.seo.redirection. Even if the possibilty exist to manage the urls via the promote panel in the frontend I think it would be better that the urls for products, categories, blog posts etc. can be managed in the backend too.

Furthermore I also want to add some connection between the menu url and the redirection urls to ensure that the menu has always the correct url. Otherwise you will be always redirected when you click on a menu entry after the related page url was changed.

What do you guys think?

Regards
Robert

**Comment by yajo** [comment]
You're welcome to open any PR on that direction, it does not seem so crazy 😋 

This addon is not perfect, so improvements are always welcome.

**Comment by lasley** [comment]
@rruebner - sounds like a decent plan IMO. I'm also planning a blog SEO module in #330. Sounds like we may have some overlap.

**Comment by rruebner** [comment]
Alright, I will create a PR with the improvements next week.

@lasley I will also create an additional PR for the customised url handling for products and product categories. Based on it we can discuss your improvements for the blog part if it is ok for you.

**Comment by lasley** [comment]
Hi @rruebner - Any update on this?

**Comment by jholze** [comment]
lets keep in mind the changes odoo did in the website builder of v11. Looks really nice.
