### ISSUE TITLE
website_backend_views doesn't scroll

### ISSUE THREAD

**Issue by gfwalters** [OCA/website#34]
I installed website_backend_views and the main partner form displays fine, but for some reason, the webpage cannot scroll up/down or left/right.  Any ideas as to what the problem could be?

**Comment by hbrunn** [comment]
I unconditionally pull all CSS from the backend, this possibly messes up things. Try to identify which css causes the problem (or if some javascript from the backend does something similar) and filter it out

**Comment by josugm** [comment]
Hi, I found what is causing the "anti-scroll" effect. In the css there are about 65 times where the option "overflow: hidden" is used. If you change them to "overflow: scroll" it starts working back again the way it should.
I don't know how to change the css in the code. I guess if you could help me with this...

**Comment by hbrunn** [comment]
you'll have to hook in here: https://github.com/OCA/website/blob/8.0/website_backend_views/view/templates.xml#L13 and not just call the template, but a modified version of it. Or, a lot simpler, reference a css file afterwards, that overrides the relevant properties with !important

**Comment by josugm** [comment]
Solved. Add
body {
  overflow: scroll !important;
}
to website_backend_views.css and scroll works again. Thanks for your help
