### ISSUE TITLE
[RFC] website_manifest: View all of the routes exposed to public

### ISSUE THREAD

**Issue by lasley** [OCA/website#369]
We have started to notice issues where pages are getting created but not documented or linked to anything. 

Google is significantly better at documenting than humans, however, so these bad pages are ending up on search results. This can be mitigated other ways obviously (published, versioning, etc), but I still find it disconcerting that a mad employee can put bad things on the website without any sort of auditing whatsoever.

This module will solve the problem somewhat by providing a view in Website Admin that shows all of the routes that are available to public facing entities (`auth="none"`). The ability to optionally filter on `website="True"` would be awesome too.

I'm not quite sure how to accomplish this one quite yet, but I'm dropping the RFC in hopes that someone knows of something pre-existing or that I'm missing. I'm pretty deep into the rabbit hole of the routing system right now 😆

**Comment by yajo** [comment]
Have you checked your `/sitemap.xml`? Not much user-friendly, but it already contains what you want if I understand you well.

**Comment by lasley** [comment]
@Yajo - good call, this is exactly what I need. Kind of verbose because it includes products and stuff, but this is just for random audits anyways - so no big deal. Closing!

**Comment by lasley** [comment]
Ps Thanks!!!!
