### ISSUE TITLE
[10.0] [website_blog_category] It's no posible create categories

### ISSUE THREAD

**Issue by Bilbonet** [OCA/website#372]
always appears the restriction (Cannot assign a parent/child relationship between categories in disparate blogs)

**Comment by XtremXpert** [comment]
I confirm the issue

"always appears the restriction (Cannot assign a parent/child relationship between categories in disparate blogs)"

If trying to create parent from the category, same error when trying to save parent

**Comment by eversatis** [comment]
I confirm the issue too. Why there is no solution for such long time?
