### ISSUE TITLE
website_multi_theme menu support

### ISSUE THREAD

**Issue by wpichler** [OCA/website#376]
I've installed the website_multi_theme addon - and got it running so far.
It does work - i do have two companies - with a website per company / per domain.

I am able to create a top level menu on the first website - but i am not able to generate a top level website menu on the second website. The menu entries are getting written - but it seems that they do not get loaded.

**Comment by pedrobaeza** [comment]
This doesn't seem anything with this module, but with Odoo itself. Does the problem happen the same on Vanilla Odoo (take into account that in standard Odoo, you can have several website, but with the same theme)?

**Comment by wpichler** [comment]
Ah - i can see what the problem was. It was missing the Top Level menu entrie. I think it would be great to generate a default Top Level Menu entrie - when the user does create a new website. But this does belong more directly to odoo - and  not oca...
But we could implement it in website_multi_theme - to be nice to the user - what do you think ?

**Comment by pedrobaeza** [comment]
No, it should be another module. You will have the same problem wanting multi-theme support or not.

**Comment by wpichler** [comment]
correct - i will create this module

**Comment by yajo** [comment]
I suggest that you add that to odoo master branch. It is more related to core odoo than to the addon.

**Comment by treviser** [comment]
@wpichler how did you create such a top level menu entry?

**Comment by wpichler** [comment]
currently manual - just use Configure Menu on website config site

**Comment by treviser** [comment]
@wpichler I tried that too, but unfortunately the Button "Create" does not react/does nothing.

**Comment by wpichler** [comment]
Do remove the default group filter which is set - then you can edit / create

**Comment by treviser** [comment]
Stupid me....thanks alot!
