### ISSUE TITLE
[Website_Multi_Theme]Wrong data (name) for theme Monglia

### ISSUE THREAD

**Issue by treviser** [OCA/website#378]
The name for theme Monglia is not written correctly, it is NOT MongOlia, but Monglia. Took me 3 hours to find out why it does not work :-)

**Comment by pedrobaeza** [comment]
Thanks for reporting! Fixed in https://github.com/OCA/website/commit/244b05adb2a5fdea82a0edb7d45f613e860e5092

**Comment by treviser** [comment]
Always welcome!
