### ISSUE TITLE
[9.0] website_snippet_country_dropdown

### ISSUE THREAD

**Issue by igallart** [OCA/website#380]
Hello, I have configured fine this module, but in web show always This error occured while compiling the bundle 'website.assets_frontend' in yellow. Is ubuntu 16.04.

I have installed all sass and gem required and lessc, but always is showed.

¿Any idea?

**Comment by lasley** [comment]
What is the exact error? There's usually significantly more information than just an error, such as file paths.

**Comment by pedrobaeza** [comment]
No if you don't even put any traceback. The modules is working fine, as you can see on runbot.

**Comment by igallart** [comment]
This error occured while compiling the bundle 'website.assets_frontend' containing:
    - /website/static/src/less/import_bootstrap.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /website_portal_v10/static/src/less/website_portal.less
    - /website_snippet_country_dropdown/static/src/css/style.sass
    - /website_form/static/src/less/website_form.less
    - /website_hr/static/src/less/website_hr.less
    - /website_portal_sale/static/src/less/website_portal_sale.less

**Comment by lasley** [comment]
@igallart - this is an installation issue, specifically with LESS. It's a bitch unfortunately and we deal with it all the time In CI.

@treviser posted help for this [here](https://github.com/OCA/maintainer-quality-tools/pull/465#issuecomment-327762729)

**Comment by igallart** [comment]
I spelled the name wrong. I'm sorry.

**Comment by lasley** [comment]
It's still an installation issue @igallart. This is evidenced by the fact that there are also core Odoo files not compiling:

```
- /website/static/src/less/import_bootstrap.less
- /web/static/src/less/variables.less
- /web/static/src/less/utils.less
```

**Comment by igallart** [comment]
@lasley, but why only when is that module installed? Before it works fine.

**Comment by pedrobaeza** [comment]
Because other modules don't require less.

**Comment by igallart** [comment]
Thanks, I'll try to solve it.

**Comment by pedrobaeza** [comment]
I recommend you to try https://github.com/Tecnativa/docker-odoo-base for avoiding this kind of problems, as it's a Docker image with all the needed things integrated.

**Comment by lasley** [comment]
Docker for the win. It's worth the time to learn it.
