### ISSUE TITLE
[website_multi_theme]Content created with the Website Builder is published on all the same pages of other websites

### ISSUE THREAD

**Issue by treviser** [OCA/website#381]
I have installed the module and I have set up different websites for different companies. When designing the /home page of one website with a user which has access only to the website of the one company, the content of this homepage is also published on the other homepages.

What can I do to avoid this?

**Comment by yajo** [comment]
I'm not aware of any `/home` controllers in Odoo, but in general terms, your views must be attached to one website or they will be considered *multiwebsite* and appear in all of them. If for any reason this does not happen automatically, locate the view in the technical area and set the right website there manually.

**Comment by treviser** [comment]
@Yajo Thanks for the feedback. During my work, I have found out that everything you do with the Website Builder on any page will be published on all the same pages of other websites. This seems to be pretty embarrassing. Does this mean that you can not use the website builder with website_multi_theme and one has to create views manually?

**Comment by yajo** [comment]
It's actually a use case that I didn't contemplate in the module. I focused on enabling assets from a given theme only for the chosen website (you see, the `_theme` suffix).

Possibly a good addition would be to be able to choose the page's website while editing it in the frontend (maybe a check box like "display this view only for this website"). This is another consequence of the multiwebsite support being only experimental in Odoo right now (something you can't notice until the *experiment* goes further, as happened after creating this addon).

So, I'll mark this as a bug, but I'm not sure if `website_multi_theme` should fix it (I guess yes) or another addon (or Odoo itself, which has the stable multiwebsite support in roadmap... but let me bet: it will land in EE and be removed from CE 😆).

**Comment by pedrobaeza** [comment]
Does this happens also without this module installed?

**Comment by yajo** [comment]
That's what I meant, yes. However, without it, you don't really notice since all websites seem the same (same theme... you know).

**Comment by pedrobaeza** [comment]
Are you sure of that? What I understand is that the same page is available for all the websites, so that's not something that has to deal with multi-theme.

**Comment by treviser** [comment]
This is my setup of the website menus, if it helps:

![selection_526](https://user-images.githubusercontent.com/1814941/30582730-1117974e-9d25-11e7-90f9-440cc079c6bc.png)

**Comment by treviser** [comment]
Is there anything I can do "manually" in the meantime until this gets fixed or Odoo makes multi-website in EE on release 13? I have to publish the second website during the next week :-(

**Comment by pedrobaeza** [comment]
Please don't blame yet to Odoo. I don't think this is something intentional for having an EE multi-website support.

**Comment by treviser** [comment]
I don't want to blame Odoo, as it will anyway not be available in the time I need it, was just responding to Yajo's joke :-)

**Comment by treviser** [comment]
I have found out that I can duplicate the following views and assign them to particular websites:
- home
- website_sale.products and the other website-product views
- aboutus
- contactus etc.

After that, I can use the website builder to design the pages and it works.

**Comment by yajo** [comment]
Indeed, that's the solution for the time being.

**Comment by pedrobaeza** [comment]
The actions I see that are needed to be done then are:

* On website creation, automatically create a homepage with this website linked.
* When creating a new page, take the current website to be linked (I don't know if this already happens).
* The only thing I don't see that can't be done easily via website builder is to modify standard pages like /contactus. If you want to have different things per website, you need to create inherited views per website.

**Comment by yajo** [comment]
I think the module is enough smartypants. Thinking in website editor UI:

- When editing a mult-iwebsite view, a button "Duplicate for this website". When clicked, opens a dialog saying "The view you are editing affects all websites. Do you want to create a copy only for this one and edit it?" Yes/no.
- When editing a single-website view, the button transforms into a message: "This page is only available in the current website".

Just with that, and proper docs, we'd get rid of this problem.

**Comment by treviser** [comment]
I'm willing to help with the docs (from a user perspective).

**Comment by pedrobaeza** [comment]
But again this is not something with this module. We can create a `website_multi_helper` (of just `website_multi`) module with that.

**Comment by yajo** [comment]
It's true, although it's hard for a user to hit the bug without it. But I agree it should be a different one.

**Comment by treviser** [comment]
@Yajo @pedrobaeza Stupid question: What is my web.base.url when using multiple websites with different domains?

**Comment by lasley** [comment]
They could probably hit this same bug once `website_multi_company` comes into play. Agreed new module

**Comment by lasley** [comment]
> What is my web.base.url when using multiple websites with different domains?

I would guess the primary website URI. As it stands, there's still going to be one primary - all outbound emails, for example, will use it.

**Comment by yajo** [comment]
@treviser https://github.com/odoo/odoo/blob/5dc1c576011d801bf5f6bbb977cdd5373d178b54/addons/website/models/website.py#L393-L406

**Comment by treviser** [comment]
@Yajo ??? (I do vaguely understand that this is getting the website domain from the hostname in the http request, but I'm not a developer...)

**Comment by yajo** [comment]
It means that your requests are bound to the website found in the http host header, or they fall back to the website with the lowest id in the db table (id=1 usually (localhost)).

**Comment by treviser** [comment]
Good to know! Thanks
