### ISSUE TITLE
Needed update version of six for website_legal_page

### ISSUE THREAD

**Issue by XtremXpert** [OCA/website#384]
The current version of six install by the current requirement.txt of odoo need to be update to get ride of the following error  

File "/opt/community/website/website_legal_page/controllers/main.py", line 7, in <module>
    from six import raise_from
ImportError: cannot import name raise_from

May be good to put a requirement.txt in this depot to upgrade six

**Comment by lasley** [comment]
`six` is an Odoo requirement, with the version frozen at `1.10.0` in [Odoo 10](https://github.com/odoo/odoo/blob/88edeeca6a17e48dca203d28c0af9d2ba2d50498/requirements.txt#L34). What version of `six` is required here?
