### ISSUE TITLE
[website_multi_theme] Problem with two websites with the same theme

### ISSUE THREAD

**Issue by yterrettaz** [OCA/website#392]
*Scenario*
*I create a new installation form official Docker image version 10 https://github.com/odoo/docker/blob/f432264ad15ce8e3326f281394e1900eb9d1c903/10.0/Dockerfile
*I load a new database with demo data and install the module website_multi_theme
*I set the demo theme for the first instance localhost and keep empty the seconde 0.0.0.0.
-> It works !

* I set the demo theme for the second instance and keep the first. I use demo theme for localhost and 0.0.0.0

-> I receive an error :
```
odoo_1  | ValueError: L'\xe9l\xe9ment '<xpath expr="//t[@t-call-assets='web.assets_frontend'][@t-js='false']">' ne peut \xeatre localis\xe9 dans la vue parente
odoo_1  | 
odoo_1  | Contexte de l'erreur :
odoo_1  | Vue `Template for replacing assets_frontend (Multi-website website_multi_theme.auto_layout_website_2 for Website 0.0.0.0)`
odoo_1  | [view_id: 314, xml_id: website_multi_theme.auto_layout_website_2, model: n/a, parent_id: 210]
```

It's possible to use 0.0.0.0 or localhost but not the both in same time.

Thank you for your help !

**Comment by yajo** [comment]
[Official docker image is outdated](https://github.com/odoo/docker/blob/f432264ad15ce8e3326f281394e1900eb9d1c903/10.0/Dockerfile#L26). [This addon requires patches that were merged after that](https://github.com/OCA/website/tree/10.0/website_multi_theme#known-issues--roadmap).

**Comment by yterrettaz** [comment]
@Yajo Thank you for your feedback, I'll check the commits specified on you readme.
