### ISSUE TITLE
Cookie Notice issue

### ISSUE THREAD

**Issue by JohnMica** [OCA/website#399]
Hi guys,

I'm running Odoo10 with a DB 9.6 on a local docker
Mounted files and db locally to see what is going on and update as needed the modules

The issue is coming with 'JsonRequest' object has no attribute 'httpsession' when clicking on the Cookie Button.

Any ideas how to sort this out, or if you do need more info ?

thanks
![screen shot 2017-11-22 at 13 48 05](https://user-images.githubusercontent.com/7076631/33130607-d15b3720-cf8b-11e7-96c9-466029be06f2.jpg)

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in runbot. If not, it's something of your installation.
