### ISSUE TITLE
[10.0] [website_anchor_smooth_scroll] Smooth scroll link broken on images

### ISSUE THREAD

**Issue by Kazebayashi** [OCA/website#406]
Hi

I just installed website_anchor_smooth_scroll and website_snippet_anchor.
Since then smooth scroll is working very well on text links, but image links do not work anymore (nothing happen on click).

The link itself is exactly the same:
Image link:
```
<a href="#anchor1" data-original-title="" title="">
<img class="img img-responsive" src="/web/image/1222" alt="" data-original-title="" title="Image link"/>
</a>
```
And text link:
```
<a href="#anchor1" data-original-title="" title="">Text link</a>
```
The anchor is set to the section tag:
```
<section class="s_big_picture bg-gray-darker mt0" style="" id="anchor1">
[...]
</section>
```

The link works when I use the full address, like `<a href="/page#anchor1"><img/></a>` but then the smooth scrolling do not work.

Any idea how to solve it?
Thanks

**Comment by Kazebayashi** [comment]
I tried on runbot and get the same result.

**Comment by yajo** [comment]
Pretty dumb failure... All we have to do is change to `event.currentTarget.hash` here: https://github.com/OCA/website/blob/28910f763ac29a2f53ce9b407cf55ff29509cff3/website_anchor_smooth_scroll/static/src/js/website_anchor_smooth_scroll.js#L14

Do you want to make the PR?

**Comment by Kazebayashi** [comment]
Thanks Yajo! It works perfectly well. 

I did the PR (#412), but I hope I did it properly (I'm not a very experienced github user yet...).

**Comment by Kazebayashi** [comment]
#412
