### ISSUE TITLE
Travis failure in 11.0 due to website_legal_page

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/website#415]
@Yajo @nadiaafa this module is provoking now a failing in Travis due to changes in upstream. Can you check?

**Comment by simahawk** [comment]
@pedrobaeza tests are green, nevertheless this hack should be removed https://github.com/OCA/website/blob/11.0/website_legal_page/tests/test_controller.py#L14 as the bug has been fixed by odoo. /cc @nadiaafa

**Comment by pedrobaeza** [comment]
Tests are not green. You can see it here: https://travis-ci.org/OCA/website
