### ISSUE TITLE
[10.0] website_sale_hide_empty_category needs products in parent category

### ISSUE THREAD

**Issue by avmediadesign** [OCA/website#416]
If a sub category (eg. cat1_sub1) contains some products but there are no products attached to the parent category (cat1), then the child category is not shown despite it contains products.
What the best way to fix this ?

**Comment by jaffaizal** [comment]
Hi avanzella,

As you can see here... 

![image](https://user-images.githubusercontent.com/7124199/36155180-9ee0f6b2-110e-11e8-8431-ea4ad1cb78c4.png)

(**Note**: that to see this... make sure that you enable "Collapsible Category List", which will show all Categories even if its empty)

![image](https://user-images.githubusercontent.com/7124199/36155430-51caca6e-110f-11e8-8870-a231077391c8.png)

Datacard is a product classified under the Website Category-->Devices/External  Hard Drive 

![image](https://user-images.githubusercontent.com/7124199/36155242-cc0c664e-110e-11e8-96fa-8bfe9179dd31.png)

As you can see below, In non-collapsible mode. Without adding the Website Categories--> "Device". It will not appear in the Category list as below shown.

![image](https://user-images.githubusercontent.com/7124199/36155667-ecd85706-110f-11e8-9c9d-33546516374d.png)

Go to the product page and add the "Device" Website Categories as shown below.

![image](https://user-images.githubusercontent.com/7124199/36155727-177bd99c-1110-11e8-9b7d-e795d3272070.png)

Then, the Parent Category is displayed as well.  **You do not need a product attached to the parent category.**

![image](https://user-images.githubusercontent.com/7124199/36155753-2f341ca2-1110-11e8-8ce8-e8a753c50e0b.png)

**Current limitation with this App/Module.** 
Empty categories are hidden when there is no product available, only if you do not enable "Collapsible Category List".

![image](https://user-images.githubusercontent.com/7124199/36156119-26881e22-1111-11e8-90a0-ecf1e6a583ce.png)


Hope this helps

**Comment by avmediadesign** [comment]
@jaffaizal,

Thank you for your comment.
IMHO, having to add products in their parent category for them to appear in their own category is not an efficient way to go especially when managing hundreds of categories. This is exactly the behaviour I was describing and that will hopefully get some fixing.
Regarding the collapsible category list issue, I faced the same problem and finally made an extension to website_sale_hide_empty_category to enable category hiding with collapsible list.
If you like, you can contact me via email and I will send you the module.

**Comment by KangOdoo** [comment]
I have an example where a empty sub category has been created in anticipation of future purchases of a new category of product. This new product has not yet been created in Odoo (10 CE) but the sub category still appears on web store. This occurs irrespective of the  position of the Collapsible Category List slider position. If this example is the intention of this app what might be the cause of this?

**Comment by pedrobaeza** [comment]
@KangOdoo that's another different issue, so don't post here about that. And your name is misleading. You don't have nothing to do with Odoo S. A., so you shouldn't name your self as `<something>Odoo` IMO.

**Comment by KangOdoo** [comment]
@pedrobaeza Thank you for your pointless post, it has done nothing to resolve an issue with this app that is needed by the OP, my business and no doubt countless other Odoo users. Often a small bug in a bit of code has more than one consequence. Sorry to hear you've been so 'misled' - a very cursory examination by you of Odoo S. A. staff names would have demonstrated that they use the name format ***-odoo and I don't.   You may have also not heard of a well known marsupial which was the inspiration for the name given my location, far from Belgium or from you for that matter.

**Comment by pedrobaeza** [comment]
OK, as said, if you have another problem with this module, open a new issue, but don't contaminate this one.
