### ISSUE TITLE
[RFC] Piwik is now Matomo, what about website_analytics_piwik?

### ISSUE THREAD

**Issue by astirpe** [OCA/website#417]
As explained in this [Piwik is now Matomo - Announcement](https://matomo.org/blog/2018/01/piwik-is-now-matomo/), we should rename the actual module `website_analytics_piwik` to `website_analytics_matomo`.

To be strict, not only the module name but also all the fields and js code should be renamed/updated as well. 
However this approach will break the backward compatibility with the running old versions of piwik servers.

In my opinion it would be convenient to add a new module `website_analytics_matomo`, and keep the former `website_analytics_piwik` for  backward compatibility. We will let the user switch the module at the time they will upgrade their analytic server from Piwik to Matomo.

I you have different opinions or better ideas, they will be appreciated.

**Comment by astirpe** [comment]
cc @hbrunn

**Comment by hbrunn** [comment]
I think there's no need to change anything, as the files to be included are still called $domain/piwik.js and $domain/piwik.php. So after an update, it just keeps working - we did that already.

A PR to the readme of the latest version specifying that Matomo is also supported, and a note for the next migration to rename the module seems sufficient to me.
