### ISSUE TITLE
"website_sale_hide_empty_category" not hiding empty categories

### ISSUE THREAD

**Issue by jaffaizal** [OCA/website#424]
Hi guys, I've just installed the above app from the ODOO store (version: 10.0.1.0.0)

Successfully installed to my website. http://www.leemporium.com
But, the empty categories are still showing. 

Have restarted ODOO server but no effect. Still showing the empty categories.

Any pointers?

**Comment by jaffaizal** [comment]
Since I could not find any documentation. And after further googling, today I found the answer after trying the following on runbot at:

https://pypi.python.org/pypi/odoo10-addon-website-sale-hide-empty-category/10.0.1.0.0

![image](https://user-images.githubusercontent.com/7124199/36150064-3f6ce4a4-10fd-11e8-98a5-209f08d23f8c.png)

But you have to remember to include the "Website Categories" in the product record.

![image](https://user-images.githubusercontent.com/7124199/36150295-2679f45e-10fe-11e8-8a7c-2502668d215c.png)

You must include all the parents and its own 'Website Categories" for the product.

**Comment by jaffaizal** [comment]
OK. After trying the above. I found a BUG with the app.

It only works if the menu is not collapsible.

![image](https://user-images.githubusercontent.com/7124199/36150931-57b2acf8-1100-11e8-8c52-1f78b055246c.png)

It does not work with collapsible menu as attached below...

![image](https://user-images.githubusercontent.com/7124199/36150711-8e3e1b64-10ff-11e8-85bb-8d920db73007.png)

**Comment by pedrobaeza** [comment]
It's not a bug, but a limitation. You can make a PR for indicating that on the README.

**Comment by jaffaizal** [comment]
Hi Pedro,

I am new here (not well verse with Github). My intention is to help others here that have downloaded the app from ODOO app store. Since it does not have any documentation attached with it, other than this following text:

![image](https://user-images.githubusercontent.com/7124199/36153385-0641a2f8-1109-11e8-9d70-47dc1b0dbfa6.png)

And there is a link back to github under the heading Bug Tracker.
Which is why I classified it as bug. (Sorry for the wrong classification)

1. Is this the link you meant for the README?

https://github.com/OCA/website/tree/10.0/website_sale_hide_empty_category

2. But what do I do next? 
3. How do I do a PR (Pull Request)?

4. BTW, can you please enlighten me how do you differentiate between a bug/issue and a limitation? 
(To me, unless there is a clearly defined statement on what the App/Module was supposed to do (which is quite clear to me by the heading). It then should work for both collapsible and non-collapsible Category List. Wouldn't you agree?)

5. Am I permissible to edit the README.rst file under the heading "Usage" to include my finding and experience on how to use the App/Module? This can be my way of contributing back to the project and community.

Keep up the good work guys!

**Comment by pedrobaeza** [comment]
Go to README file, and you will find an "Edit" button there. Click on it and you will be able to change the README and propose a PR to the main repository.

**Comment by jaffaizal** [comment]
Hi Pedro,

Thanks for the info. In this case the PR is a functional request to include that it should also works for collapsible website categories?

Jaf

**Comment by pedrobaeza** [comment]
See complete README template: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

There's a section called "Known issues / Roadmap" to express that things.
