### ISSUE TITLE
[RFC] Image lazy load

### ISSUE THREAD

**Issue by simahawk** [OCA/website#425]
I'm willing to implement a reusable solution to do.... well, loading image lazily :)

I haven't spot any solution in this repo nor on the web. Is there anything I missed?

If no solution is there, I still have to decide which lib to use. I'll name a bunch:

1. http://jquery.eisbehr.de/lazy/ (we already have jquery, not a burden)
2. http://dinbror.dk/blazy/
3. https://github.com/verlok/lazyload

another super-light and nice solution (coming from Medium) which blurs images before loading:

4. https://github.com/craigbuckler/progressive-image.js

Any opinion?

/cc @Yajo @lasley ( in case you've already played w/ it :stuck_out_tongue_winking_eye: )

**Comment by simahawk** [comment]
No matter which lib we include it might be worth to put it in the new repo mentioned here https://github.com/OCA/web/issues/842

**Comment by yajo** [comment]
I have no idea on which one would be best, never used such tools.

As a suggestion, check if there's any upcoming W3C standard, and if there's any polyfill available. In any case I'd expect it to "just work" out of the box with all images once the addon is installed.

**Comment by simahawk** [comment]
@Yajo +1 for W3C / polyfillcheck. 

Regarding "just work" yes... if you are in control of the markup.
But to get that working w/ all the images we'll have to introduce a sort of html transform before sending it back to response (maybe on `render` call): `img` elements and `div` + bg image should be converted to `data-src` (or alike) otherwise browsers will fetch them anyway before JS hooks in.

**Comment by tarteo** [comment]
@simahawk Are you already or still working on this? Would be really nice to have.

**Comment by simahawk** [comment]
@tarteo had not time to invest on this so I went for http://jquery.eisbehr.de/lazy + small custom code to get the result for the customer. I still have this in mind tho + automatic image scaling in a controlled way (but this is another story :wink:)

**Comment by simahawk** [comment]
implemented here https://github.com/OCA/website/pull/507
