### ISSUE TITLE
Website Form Builder - How to set recipient email address?

### ISSUE THREAD

**Issue by Shiraj-Nisus** [OCA/website#431]
Hello,
We are testing this (https://www.odoo.com/apps/modules/10.0/website_form_builder/) module on Odoo v10 (both community and enterprise).When select "Send an Email" form setting there is no place to enter recipient email address.Is this a bug or that feature has not implemented?

**Comment by bradbendy** [comment]
I just looked at this, and v11 has it. Have you tried on runbot? I remember reading somewhere (I think), that if certain SMTP options are not set then certain fields won't appear.

**Comment by pedrobaeza** [comment]
This is not something of the module, but the Odoo options, so I close.
