### ISSUE TITLE
[11.0] Form builder not adding multiple leads

### ISSUE THREAD

**Issue by bradbendy** [OCA/website#432]
Hi,

I tested this on enterprise-11 runbot as well as Odoo 11.0+e-20171229 (Enterprise Edition).

When adding a new form using form builder and selecting the "Create a lead" as the action, the first lead you submit adds to the leads correctly. When you go to add a second lead (refreshing the page), you get the success message but the first lead you added shows as updated, and this log appears on the server.

2018-03-08 21:01:04,263 1308 WARNING fch_master odoo.models: Comparing apples and oranges: utm.medium(1,) == 1 (/usr/lib/python3.6/site-packages/odoo/models.py:4607)
2018-03-08 21:01:04,264 1308 WARNING fch_master odoo.models: Comparing apples and oranges: crm.team(1,) == 1 (/usr/lib/python3.6/site-packages/odoo/models.py:4607)

I also tried adding more field, like phone number, city, state, zip, etc and I get these errors.

2018-03-08 19:20:36,572 1308 WARNING fch_master odoo.models: Comparing apples and oranges: res.country.state(212,) == 212 (/usr/lib/python3.6/site-packages/odoo/models.py:4607)
2018-03-08 19:20:36,572 1308 WARNING fch_master odoo.models: Comparing apples and oranges: res.country(3,) == 3 (/usr/lib/python3.6/site-packages/odoo/models.py:4607)
2018-03-08 19:20:36,576 1308 WARNING fch_master odoo.models: Comparing apples and oranges: utm.medium(1,) == 1 (/usr/lib/python3.6/site-packages/odoo/models.py:4607)
2018-03-08 19:20:36,576 1308 WARNING fch_master odoo.models: Comparing apples and oranges: crm.team(1,) == 1 (/usr/lib/python3.6/site-packages/odoo/models.py:4607)

Attached is what the lead show on the activity. Don't think this is anything I caused/doing wrong as the same exact thing occurs on the runbot.

Please let me know if I can do any more testing or give any more insight!

Thanks
![odoo-form-leadf](https://user-images.githubusercontent.com/6732542/37176386-75b756e6-22d9-11e8-831b-db42b191341d.jpg)

**Comment by pedrobaeza** [comment]
I think you are doing wrong to refresh again the POST command. You have to start from the beginning.

**Comment by bradbendy** [comment]
Yeah, tried that as well. Ive reloaded the page with just the URL, also
tried a inconginto and on a different computer. Super confused!

**Comment by bradbendy** [comment]
Did some more testing with the default (did not change anything) contact us form. Same thing happens! It just shows "Other value given for field" in that 1st lead. If I trash that lead, I can create it again then same thing happens when I go to do a 2nd, 3rd, 4th, etc. 

Only thing I can think of is if it's tracking it by IP address. So I tried from my phone on the celluar network and the lead added as a brand new one. Went to contact form again and same odd behavior, it showed up as "Other value given for field". As a further test - put my cell phone back on wireless so the same IP address as the desktop and it added a 3rd entry to the same lead that was started from the cell phone.

So it appears the form "works" but they cannot fill out the form more then once and have create more then one lead. I guess this does makes sense in a way, only question I have is, what about if they are from a shared computer or something? Not sure how it's tracking this stuff exactly. I tried from another browser and a new lead was added, so must be cookie driven or something?

With the current behavior the one problem I see is, what if we have someone entering information onto the forms that are for different leads/companies, then all that info goes under "one lead" when it really should be multiple ones.

Thanks!

**Comment by pedrobaeza** [comment]
@bradbendy this is a bit outside the scope of the module then, but @Yajo can you check if this affects us?

**Comment by yajo** [comment]
Sorry, I cannot reproduce. Please notice that the addon has not yet been ported to odoo v11, so incompatibilities may exist.

Please try to reproduce it on [this repositorie's 10.0 runbot](https://runbot.odoo-community.org/runbot/repo/github-com-oca-website-186), and if you manage to do it, upload a video here so we can see the STR, and reopen.

Thanks!

**Comment by pedrobaeza** [comment]
Oh, I didn't even see the version, but how can you try to put a module in other version??!! Of course that's not going to work.
