### ISSUE TITLE
[10.0] website_form_builder: many2one field appear static

### ISSUE THREAD

**Issue by abdallamhafeez** [OCA/website#437]
Steps:
- Create form in website page contain field has type many2one
- Add in backend new record

Current Behavior:
New records does not appear in website form

Expected Behavior:
Make field in website dynamic or updated with backend new records

**Comment by pedrobaeza** [comment]
That's the expected behavior, as you can select specific items of the many2one to not be shown. If you want to refresh values, just delete and re-add the field.
