### ISSUE TITLE
can't install website_multi_theme

### ISSUE THREAD

**Issue by drinktea0808** [OCA/website#485]
hello, 

i can't install this module on V11 CE and EE. an error kept appearing "Unable to install module "website_multi_theme" because an external dependency is not met: Unable to find 'sass' in path"

i follow these 3 guides and can't get it to work

1 - https://www.odoo.com/forum/help-1/question/ubuntu-16-04-how-to-install-sass-for-odoo-123090
2 - https://github.com/OCA/maintainer-quality-tools/pull/465
3 - https://travis-ci.org/OCA/website/jobs/255170761

can i get help on how to fix this on Odoo v11 ? thank you

**Comment by pedrobaeza** [comment]
Sorry, this is a deployment question. You have to install saas. Look in Google how to do it for your operating system.
