### ISSUE TITLE
Cookie appear after I accept in header.

### ISSUE THREAD

**Issue by BalramY** [OCA/website#486]
Current Behaviour:
Cookie popup is removed after I accept cookie But If I login and logout then it is again appear.

Expected Behaviour:

Once I accept cookie, then it should not display for specific time(no matter I login or logout)

**Comment by pedrobaeza** [comment]
That's expected, as the acceptance is saved on the session itself. If not, you need to create a cookie for saving the cookie acceptance, what is somehow ironic if you don't accept it.
