### ISSUE TITLE
website_backend_views doesn't display form

### ISSUE THREAD

**Issue by bjoliveau** [OCA/website#49]
Hi, 

I've created a new database with demo data.

I installed the module and go to http://localhost:9999/website_backend_views/demo/ on my local server.

The page shows up then, but without the form (screenshot below)

![001_201506_2f9](https://cloud.githubusercontent.com/assets/1226478/8385221/d6e58876-1c14-11e5-84ff-0454d9843245.png)

It seems i followed advices in "usage" part of README.rst, but no form appeared. 

What i missed ?

**Comment by hbrunn** [comment]
Did you verify (in debug mode) that `website_backend_views/static/src/js/website_backend_views.js` is loaded? If so, what happens if you look at the source code? Do you see a line like `<t t-website-backend-view=...` between the title and the text?

**Comment by bjoliveau** [comment]
We installed a new instance and clone code. It's fine and the form appear.
Thanks for your help.
