### ISSUE TITLE
[11.0] "website_anchor_smooth_scroll" disables #0 scroll to top

### ISSUE THREAD

**Issue by lucode** [OCA/website#490]
Many Odoo themes come with a button at the bottom of the website to easy scroll back to the top. This is done through the relative link #0.
But the website_anchor_smooth_scroll module breaks this behaviour. It only works when I manually ad the ID="0" in the top section of the page.

**Comment by pedrobaeza** [comment]
Do you have any possible solution?

**Comment by lucode** [comment]
I'm not experienced with frontend coding. But I think a kind of exception in the case of the ID="0" would work. Normally this ID will not be used for something else.
I have just seen that for instance Odoo SA themes are using only # and not #0 in the Go back to top button.

**Comment by yajo** [comment]
> Many Odoo themes come with a button at the bottom of the website to easy scroll back to the top. This is done through the relative link #0.

Then the bug is in those themes. They should link to `#wrapwrap` instead, which would work in any case. You can change the footer link in your odoo instance if you install them and cannot patch them upstream.
