### ISSUE TITLE
Travis is broken on 11.0 OCA/website

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/website#494]
I've find out that modules website_logo and website_multi_theme have broken test on Travis.
I can't figure out if my PR broke it or it was already broken, so please I need some help.
https://travis-ci.org/OCA/website/jobs/410391854

Thanks,

**Comment by HviorForgeFlow** [comment]
Closed as now seems to be fine

**Comment by pedrobaeza** [comment]
Yes, I have restarted the build as it was a temporary glitch.
