### ISSUE TITLE
Question: access of page by direct-link

### ISSUE THREAD

**Issue by rgl1234** [OCA/website#497]
Hello
Does the module "website_menu_by_user_status" support to restrict the visibility of a page also, if the page is accessed by a direct-link, or does it only remove the menu-item but the page stays accessible if someone knows the direct link?

**Comment by pedrobaeza** [comment]
Which module?

**Comment by rgl1234** [comment]
website_menu_by_user_status

**Comment by pedrobaeza** [comment]
No, it doesn't. It also hide/show website menus.
