### ISSUE TITLE
website_multi_theme is not uninstallable

### ISSUE THREAD

**Issue by yelizariev** [OCA/website#498]
I haven't tried yet, but pretty sure, that there is no clean up on uninstallation ``website_multi_theme``. It means that view duplicates are kept and make a mess. I guess some ``uninstall_hook`` has to be added

**Comment by yajo** [comment]
I think you have to confirm this problem. AFAIK, all the multiwebsite views are XMLID-tagged with `website_multi_theme` namespace, which makes all of them get deleted automatically when uninstalled.

However, there would be a problem with original views being disabled, so in any case possibly we need that hook indeed.
