### ISSUE TITLE
[11.0] website_crm_privacy_policy: translation broken

### ISSUE THREAD

**Issue by ghost** [OCA/website#505]
Translations not included on website.

**Comment by pedrobaeza** [comment]
What do you mean?

**Comment by ghost** [comment]
https://buergerwerk.eu/contactus

the translation is not included, uses english

**Comment by pedrobaeza** [comment]
Synchronize translations.

**Comment by ghost** [comment]
I load the Translations again. The translation i made in last day will be set, but not this translation.

**Comment by chienandalu** [comment]
Looks like the .pot hasn't been properly generated: https://github.com/OCA/website/blob/11.0/website_crm_privacy_policy/i18n/website_crm_privacy_policy.pot

**Comment by pedrobaeza** [comment]
It's got automatically. Try to generate it manually to compare.

**Comment by chienandalu** [comment]
Ok, it's ok indeed. There's no translatable text in this module. The message is in a t-call that loads this view: https://github.com/OCA/website/blob/11.0/website_legal_page/views/reusable_templates.xml#L5-L10

So is that module the one to be translated.
