### ISSUE TITLE
[11.0] website_legal_page

### ISSUE THREAD

**Issue by ghost** [OCA/website#508]
-> keep it simple

i want use the this module for my site. I translated the site "fast & dirty" into german, because every business needs individual terms.

The Problem are the "hardcoded" areas with informations about the Company and e. g. in Terms of Use the field with relation to the law of the home-country.

This System makes a individual design unpossible.

I think it's great that there is the possibility that the user must agree to the rules in the contact form and the cart (and registration -> todo)

What do you think? Could we use templates for the Terms of Use, Privancy Police and Legal Advice with only changeable areas?

**Comment by ghost** [comment]
@chienandalu

**Comment by chienandalu** [comment]
I guess they could be split and be called independently. You should provide backwards compatibility to avoid breaking other modules anyway.
