### ISSUE TITLE
[8.0] Broken travis build on linting

### ISSUE THREAD

**Issue by simahawk** [OCA/website#518]
many errors like this
```
website_blog_share/README.rst:27: [E7901(rst-syntax-error), ]  Title underline too short.||Know issues / Roadmap|====================
website_blog_share/README.rst:27: [E7901(rst-syntax-error), ]  Title underline too short.||Know issues / Roadmap|====================
```

**Comment by pedrobaeza** [comment]
Yeah, they have arisen because the check was incorporated later. Can you please fix them directly?

**Comment by nikul-serpentcs** [comment]
@pedrobaeza I have already Done but, Travis It seems it's stalled. Let's wait a bit.

**Comment by simahawk** [comment]
closed here https://github.com/OCA/website/commit/15483541a2072c50f1faeb1b53866e47bc5ef359

**Comment by simahawk** [comment]
There you go https://github.com/OCA/website/issues/523
