### ISSUE TITLE
Website Menu hide

### ISSUE THREAD

**Issue by prakashjain** [OCA/website#525]
"website_menu_by_user_status" odoo 11.
Example:
Website Home, Contact us menu created using "website.page" object and able to hide.
And Website Forum, Blog and custom menu created using "website.menu" object and unable to hide.
Is there any way to hide menu created using  "website.menu" object?. using this plugin

**Comment by pedrobaeza** [comment]
Not right now. You need a website.page record.

**Comment by prakashjain** [comment]
I would like to hide website menu if user cannot login, only visible after login into the system website menu. Example: Forum, Blog and some custom menu. Please let me know if  any possible solutions.

**Comment by pedrobaeza** [comment]
As said, not right now.
