### ISSUE TITLE
Move `website_sale_line_total` to OCA/e-commerce

### ISSUE THREAD

**Issue by simahawk** [OCA/website#526]
See https://github.com/OCA/website/pull/492

**Comment by simahawk** [comment]
@pedrobaeza not sure w/ should actually take action here... I see some other modules: I guess `e-commerce` repo came after?
In any case it might a breaking change for many ppl if we move them out on v10 (I don't see them in v11).

**Comment by pedrobaeza** [comment]
Yeah, that was the reason. We created OCA/e-commerce after a while when we see that OCA/website is very populated with e-commerce related stuff.
