### ISSUE TITLE
[RFC] Language specific attachments and links.

### ISSUE THREAD

**Issue by tschanzt** [OCA/website#537]
Currently in odoo we are only able to translate text. This is an issue as it is not possible to change elements like attachments or links according to the Language. For instance if one has a nice graphic explaining something you either will have to make it language neutral or include it multiple times for each language which both aren't satisfactory solutions. 

How would/do you handle this issue? 

Currently we're thinking about adding a custom model, which has a parent_id and child_ids, language and a link or attachment_id. The one without parent_id is considered the default one. and is reachable over a controller, which then redirects from the original url to the correct url in the langauge.

**Comment by pedrobaeza** [comment]
By attachments do you mean images? In odoo v12 these contents are supposedly translatable. Have you tried?

**Comment by tschanzt** [comment]
@pedrobaeza Could also be a pdf or something. I checked on runbot and i didn't see anything like that for the image it still is just the alt text which is translatable.

**Comment by simahawk** [comment]
@pedrobaeza anything that can be linked (let's say an image or a video is a link to another resource) and that might have a specific per-language content.

What I see on runbot is 
![image](https://user-images.githubusercontent.com/347149/48704326-86273a00-ebf6-11e8-8eb6-5947160adf2d.png)
so you can edit only ALT on images

For a video you don't have nothing AFAIS.

**Comment by pedrobaeza** [comment]
OK, I see. And isn't better to work directly on a feature for having specific pages per language?

**Comment by simahawk** [comment]
@pedrobaeza that's exactly my goal in the CMS perspective, but it's a long journey as you have to turn off all the translated-related feature for pages (or whatever the content is) and it changes the std paradigm for handling translations (you have to pay attention to UI/X).

This one was more a proposal for an easy as possible hack to get the result w/ less effort fully integrated w/ standard Odoo CE ...and also a ping to contributors to see how/if they dealt w/ such issue so far :wink:

**Comment by pedrobaeza** [comment]
Well, I think all these workarounds at the end takes more time than simply go for the full-packed solution. Although UI is important, I don't think it's too difficult to get this system properly plugged:

- When you click on Translate, ask to use current translate system or create a new translation page. If second, then copy current one with language and go to it.
- Handle all the controller stuff through a field language at website.page level. If there's no specific page for that level, go to the general one.
- When clicking on translate again on a page with translation page, go directly to it.
- Include the possibility of removing the translation page (it's already I think).

**Comment by simahawk** [comment]
> When you click on Translate, ask to use current translate system or create a new translation page. If second, then copy current one with language and go to it.

I don't think we should make the user choose: if you install this feature and the current model has this behavior implemented it must always be applied

> Handle all the controller stuff through a field language at website.page level. If there's no specific page for that level, go to the general one.

Page retrieval happens into ir_http, at least from v11.
You need to link the canonical record and the translations, you must be able to retrieve them at any time (for instance you must use them for alternative URLs)

> When clicking on translate again on a page with translation page, go directly to it.
Include the possibility of removing the translation page (it's already I think).

You also have to override page enumerations: you must pull in translated versions only and it would be better to not list a page if is not translated in that language.

Then you have page management, which as usual has very few - if none - hooking points.

So, all in all there are *a  lot* of places (many probably missing in this list) where you have hack and make sure everything works smoothly together.

We should go in that direction, of course, but if we could find a cheap solution for the short term, it would be nice :)

**Comment by pedrobaeza** [comment]
OK, as you prefer.
