### ISSUE TITLE
12.0 mig website_canonical_url

### ISSUE THREAD

**Issue by mfigueiredo-odoogap** [OCA/website#545]
starting migration off website_canonical_url

**Comment by pedrobaeza** [comment]
Where is that migration?

**Comment by mfigueiredo-odoogap** [comment]
i'm starting it today

**Comment by pedrobaeza** [comment]
Then please don't add a new issue, and just mention in the migration issue that you want to be assigned to that module. I'm writing that now, so no more actions needed for this one, but take into account for the future.
