### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Himmawari** [OCA/website#55]
module: website_sale_vat_required
version: 8.0

**Steps to reproduce**
- Put the folder in addons, refresh modules in the backend, install the module and when I installed it I have error

**Current behavior**
Error. It doesn't works

Print screen:
https://drive.google.com/file/d/0BxBxgOREo-YoRDExVmhGRjJDZUU/edit?pli=1
https://drive.google.com/file/d/0BxBxgOREo-YoVDlseWZlWFV3dHc/edit?pli=1

**Comment by yajo** [comment]
This is probably due to having customizations in view, and probably fixed in newer versions (the issue is quite old). So, closing. Reopen if needed.
