### ISSUE TITLE
After installing module Website Snippet Anchor I get this error

### ISSUE THREAD

**Issue by iqs-systems** [OCA/website#550]
Error:
Uncaught Error: Can't load template /website_snippet_anchor/static/src/xml/link_dialog.xml?debug=1544446255182, http status 404

https://mysite.com/web/content/514-c82dc0d/web.assets_common.js:3618
Debuging:
Error: Can't load template /website_snippet_anchor/static/src/xml/link_dialog.xml?debug=1544446255182, http status 404
    at XMLHttpRequest.<anonymous> (https://mysite.com/web/content/514-c82dc0d/web.assets_common.js:3633:169)

**Comment by pedrobaeza** [comment]
Sorry, but without more details this can't be answered. It's probably how are you deploying the addon, but can't say more.

Closing this while no more information is provided, but can be opened again if needed.
