### ISSUE TITLE
[10.0] [website_seo_redirection] ecommerce with category

### ISSUE THREAD

**Issue by baba75** [OCA/website#562]
When using the SEO redirection on products page, example:
/shop/product/product-name-a-b-1725  --> /shop/product-name
And the products are organized in categories, the category is not passed correctly in the URL.
The result will be:
/shop/product-name?category=<werkzeug.datastructures._omd_bucket+object+at+0xaec44c0c>
instead of:
/shop/product.name?category=10
As a consequence the server will answer with '500: Internal Server Error'

**Comment by pedrobaeza** [comment]
I don't think this is something of the module itself. Try to use the other type of redirection.
