### ISSUE TITLE
[11.0][website_lazy_load_image] not changing img attribute to data-src

### ISSUE THREAD

**Issue by rowemoore** [OCA/website#569]
module: website_lazy_load_image
version: 11.0

**Steps to reproduce**
Install module

**Current behavior**
img tag is not changing "from src="  to  "data-src="  regardless of css class.

**Expected behavior**
That the tag would change and the lazy js would be triggered.

I've tested this on my own build and on the runbot for the OCA where it was already installed.

**Comment by tarteo** [comment]
How do check that data-src is not there? For website publishers this is not active only for actual visitors. Try to go to your website without logging in.

**Comment by rowemoore** [comment]
I checked it as a public (not logged in) user.  Check out the [OCA Runbot](http://3355845-11-0-3d29dd.runbot1.odoo-community.org/) and see if I am missing something. Is it possible another module has been installed that is overriding the render_template method?

**Comment by rowemoore** [comment]
Okay, I've looked at this some more and now see the data-src attribute.  For some reason it doesn't show in chrome dev tools but does in page source.  Sorry for the confusion.  Probably need to adjust something in dev tools. 
To show you what I  am  seeing, here is the same page as an anonymous user:
![screenshot 104](https://user-images.githubusercontent.com/14188201/52816237-ad56a180-3055-11e9-810d-306f32c40bdf.jpg)
![screenshot 105](https://user-images.githubusercontent.com/14188201/52816244-b182bf00-3055-11e9-89a7-a405471db712.jpg)
