### ISSUE TITLE
[11.0] Website Form Builder: *Required Fields

### ISSUE THREAD

**Issue by UnixedIT** [OCA/website#584]
Hello, 

When Submitting the Form without "user log in" all mandatory fields appear as optional fields.

please find the attached 1.png.

if the user log-in there is no problem as attached  2.png.

![1](https://user-images.githubusercontent.com/32422485/54866122-e1219700-4d78-11e9-95ec-a32abfea5305.png)
![2](https://user-images.githubusercontent.com/32422485/54866123-e1219700-4d78-11e9-8012-b6c79280d810.png)

**Comment by yajo** [comment]
See fix at #585

**Comment by UnixedIT** [comment]
Thank you @Yajo for fixing. 

-as you know-please note the fix is working for Styling only. but the public users still able to submit the form event they don't fill the mandatory fields.

**Comment by seyuf** [comment]
@pedrobaeza can you please reopen this? As the issue is still there.
The css has been fixed but the wrong behavior is still there. I.e
![required-field-not-set](https://user-images.githubusercontent.com/3765910/65377528-9d6b0400-dcad-11e9-9655-33357980fc31.png)

The form appears valid even though the email (courriel) field has not been filed.
On the screenshot, one can notice the say input is missing the required attribute like on the first one.

Possible workaround: set `required="required"` through the html editor

**Comment by rafaelbn** [comment]
Dear @seyuf , reproduce the error here in runbot. I cannot reproduce:

http://3385143-12-0-9bc24f.runbot2-2.odoo-community.org/

![2019-09-21_21-51-58](https://user-images.githubusercontent.com/8736623/65378582-94ccfa80-dcba-11e9-8e73-2268c4cb492d.png)

**Comment by seyuf** [comment]
Hi @rafaelbn ,
Im using odoo 11 after a quick test on your runbot.
The form is sent as long as the first field is filled. Which shouldn't be the case.
It should be sent only when all the required fields are.
![error-required-field](https://user-images.githubusercontent.com/3765910/65378670-28eb9180-dcbc-11e9-8847-6b7ffabd3caf.jpeg)

Also, on my version, the backend check, contrary to the runbot, considers the form as valid.
Maybe we're not using the same version of the module. I'll check and keep you posted tomorrow.

**Comment by pedrobaeza** [comment]
You can't try this on runbot without uninstalling `website_form_recaptcha`, as both are incompatible. Remove it and all should be OK.

**Comment by seyuf** [comment]
Also i believe the runbot is under Odoo12? The issue has been detected on odoo 11.

**Comment by seyuf** [comment]
@rafaelbn has mentioned by @pedrobaeza, i just removed recaptcha plugins from the runbot.
The form is sent and considered as valid on odoo12 as well. You can test now.
![wrong-form-required](https://user-images.githubusercontent.com/3765910/65378813-62bd9780-dcbe-11e9-90b8-486e59fbb925.jpeg)

**Comment by pedrobaeza** [comment]
There is runbot for both 11 and 12. Just click on the appropriate one.

**Comment by seyuf** [comment]
Yep as stated above the issue seems to be present on 11 & 12.

**Comment by pedrobaeza** [comment]
OK, reopening for now until further investigation

**Comment by pedrobaeza** [comment]
@Yajo can you check?

**Comment by rafaelbn** [comment]
OK, so uninstalling `website_form_recaptcha` the BUG occurs:

![2019-09-22_13-33-15](https://user-images.githubusercontent.com/8736623/65386595-13b74700-dd3e-11e9-833e-a56ca6ab8750.png)

**Comment by seyuf** [comment]
Can someone reopen this, please?
@pedrobaeza, if possible, sorry to bother.

:pray:

**Comment by pedrobaeza** [comment]
The fix is already merged.

**Comment by seyuf** [comment]
Ha? If that's the case my bad then.
Thanks for the info.

**Comment by pedrobaeza** [comment]
Check #585

**Comment by seyuf** [comment]
@pedrobaeza  Nope, that seems to be the old fix that didn't work. If you read the thread again you'll understand.

**Comment by pedrobaeza** [comment]
Well, in any case, if nobody has already fixed this, nobody is going to do it, and that's the goal of the triage.

**Comment by seyuf** [comment]
Yeah that's what i just realized. We were planning to move away from v11, i guess this will speed things up.
Thanks anyway.
:pray:

**Comment by pedrobaeza** [comment]
Yes, it's very advisable, as this version is not receiving official patches since 2 years ago, and that's a security risk. There has been also very good improvements both in functional and framework areas during these years.
