### ISSUE TITLE
website_addthis Raise website Title Chaos

### ISSUE THREAD

**Issue by eversatis** [OCA/website#591]
After website_addthis installed and configured, you will find a string "FacebookTwitterPrintEmailAddThisFacebookTwitterPrintEmailAddThis" added to the end of Home Title in the promote SEO page. If you remove it, it will repeat the set Title several times after you refresh the page.
Reproduce: You need edit the home page title first after website_addthis installed and enabled. The issue would not be raised until you edit it once website_addthis is enabled. 
Delete the string "FacebookTwitterPrintEmailAddThisFacebookTwitterPrintEmailAddThis"  and save again, you will see you title is repeated for several times after refresh.

![title](https://user-images.githubusercontent.com/10336015/56565604-618b2000-65e3-11e9-9008-451f3df7b8e5.png)

**Comment by JonathanOsAlc** [comment]
@frankmiao2015 which version is?

**Comment by eversatis** [comment]
@JonathanOsAlc I use version odoo 12

**Comment by simahawk** [comment]
Seems a duplicate of https://github.com/OCA/website/issues/493
