### ISSUE TITLE
[10.0] Weblate tranlation is empty

### ISSUE THREAD

**Issue by jarmokortetjarvi** [OCA/website#605]
(This should probably be in a transbot-repo, but couldn't find where it is)

Auto-generated translation is empty, even though it is done in Weblate.

Weblate translation:
https://translation.odoo-community.org/projects/website-10-0/website-10-0-website_signup_legal_page_required/fi/

Related commit:
https://github.com/OCA/website/commit/666a0a8b900f0e0074e4a7922aa787b73253ec7e

**Comment by pedrobaeza** [comment]
@sbidoul any idea?

**Comment by sbidoul** [comment]
@jarmokortetjarvi fi.po looks fine for this module: https://github.com/OCA/website/blob/10.0/website_signup_legal_page_required/i18n/fi.po. There was a commit just after the one you mention.

**Comment by sbidoul** [comment]
Closing, do not hesitate to reopen if I missing something.

**Comment by jarmokortetjarvi** [comment]
Yes, I was looking at the wrong (empty) commit. My mistake!
