### ISSUE TITLE
[10.0] travis build fails

### ISSUE THREAD

**Issue by tbaden** [OCA/website#629]
the module website_sale this causing the build TESTS="1" ODOO_REPO="odoo/odoo" to fail.

2019-05-11 17:04:24,146 7269 ERROR openerp_test odoo.addons.website_sale.models.sale_order: Fail to find pricelist for partner "Public user" (id 5)

to see in PR:
https://github.com/OCA/website/pull/567
https://github.com/OCA/website/pull/624
https://github.com/OCA/website/pull/625

First occurance around 11 june 2018 PR: https://github.com/OCA/website/pull/479
Correction: 479 was rebuild 3 months ago. First ist occurance ist 567 4 month ago, so far

**Comment by pedrobaeza** [comment]
@sergio-teruel is this the error you have mentioned before?

**Comment by tbaden** [comment]
currently struggeling to reproduce this error locally, but I'm on it.

**Comment by tbaden** [comment]
after some late night investigation it seems that website_sale_line_total and website_sale_hide_empty_category are both causing this issue. disabling just one of them still causes the issue.it's not Website_sale either, added this dependency in unrelated repo(project) without any issues. Must be a combination of different dependencies. further investigation is planned for tomorrow, to find the cause and a fix for this.

**Comment by tbaden** [comment]
the test:
```
    def test_127_0_0_1(self):
        """Check 127.0.0.1 downloads its default assets."""
        response = self.url_open("http://127.0.0.1:%d" % PORT, timeout=60)
        self.assertEqual(response.getcode(), 200)
        ...
```
is the cause of all this. seems like urllib2 has problems with 127.0.0.1. this needs further investigation, but the train wifi is killing my researches...
in v11 it got changed to:
```
    def test_0_0_0_0(self):
        """Check 0.0.0.0 downloads its default assets."""
        response = self.url_open("http://0.0.0.0:%d" % PORT, timeout=60)
        self.assertEqual(response.status_code, 200)
        ...
```

@pedrobaeza do you know by any change any known issues with urllib2 and 127.0.0.1.
was there a travis update or somehting like this around january/february? this would explain the spontaneous error.

btw.
```
    def test_localhost(self):
        """Check localhost downloads its multiwebsite-enabled assets."""
        response = self.url_open("http://localhost:%d" % PORT, timeout=60)
        self.assertEqual(response.getcode(), 200)
        ...
```
is working just fine.

**Comment by tbaden** [comment]
https://github.com/OCA/website/pull/398#discussion_r150485077 no real reason mentioned for this change, but most likely the same reason

**Comment by tbaden** [comment]
@Yajo any experience with urllib and failing tests when using ip?

**Comment by tbaden** [comment]
missed the obvious. creation of 
            ip = env["website"].create({
                "name": "127.0.0.1",
                "domain": "127.0.0.1",
                "multi_theme_id": False,
            })
but pricelist computation gets no pricelist for the new id. looking for recent changes on this kind of topic

**Comment by tbaden** [comment]
Currently Not in the Office, but most likely found the commit, just some Tests needed. Update follows in the following days

**Comment by Yajo** [comment]
Hi there.

I'm not sure what's the source of this problem. It might be that the `website_multi_theme` addon is installed before others, which could make main website not get the views added by other addons. In such case, you should split travis jobs to test that addon separately from the others, using INCLUDE and EXCLUDE vars, setting the matr

**Comment by yajo** [comment]
Hi there.

I'm not sure what's the source of this problem. It might be that the `website_multi_theme` addon is installed before others, which could make main website not get the views added by other addons. In such case, you should split travis jobs to test that addon separately from the others, using `INCLUDE` and `EXCLUDE` vars, setting the `matrix` key in `.travis.yml` like:

```yaml
matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="website_multi_theme"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="website_multi_theme"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="website_multi_theme"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="website_multi_theme"
```

However, the test suite is actually passing well. The thing that is failing is the little piece of code that we have at OCA that makes sure there are no `ERROR`, `FAIL` or `WARNING` logs. You can fix this just decorating [the test that is failing](https://travis-ci.org/OCA/website/jobs/538933126#L1473) with `@odoo.tools.mute_logger("odoo.addons.website_sale.models.sale_order")` (which is the logger that logs the `FAIL` line).

**Comment by tbaden** [comment]
@Yajo there was a recent change which switched to multi pricelist computation in v10, most likely a missed clause in the changes.

**Comment by tbaden** [comment]
as I was a little sidetracked by my actual work I forgot to work on this one. Will start another debug session on this weekend to finally fix this.

**Comment by NL66278** [comment]
I do not know why other projects using website_sale on 10.0 are not showing the same errors, but checking in runbot shows that indeed the public user does not have a pricelist set. Probably due to the fact that it is an inactive user, so probably not seen when pricelists are activated.

The obvious solution to me seems to be to give the public user the default pricelist.
