### ISSUE TITLE
https://github.com/OCA/website/issues/15

### ISSUE THREAD

**Issue by jbgraffiti** [OCA/website#641]
hi

I get exactly this issue (v.8) ONLY when I have created a duplicate event from the drop down menu.
" ('ValidateError', u'Error while validating constraint\n\nNo more available seats.')"

-original event - works with user logged on - max seats specified, no ticket type. free ticket, user registered

duplicate copy of original event - exactly the same but traceback error
![Internal_Server_Error](https://user-images.githubusercontent.com/41232670/58541387-53887a80-81f3-11e9-80da-0c8454571b4f.jpg)
Please advise

Many thanks Jon

training.baxterthompson.com

**Comment by pedrobaeza** [comment]
The error is clear: you don't have more seats. Free some of them.

**Comment by jbgraffiti** [comment]
thankyou pedro 

----- Original Message -----
