### ISSUE TITLE
website_js_below_the_fold brakes Odoo Paypal integration

### ISSUE THREAD

**Issue by walkerblackwell** [OCA/website#648]
When this plugin is turned on the redirect url from Paypal back to the odoo site does not work. The payment is not registered as paid. This is due to the javascript not being available.

There needs to be a way to keep the payment gateway javascripts at the top.

best,
Walker

**Comment by tarteo** [comment]
Which module / version.

**Comment by walkerblackwell** [comment]
V12 Enterprise, Odoo.sh, js below the fold.

Sorry, meant to put that detail in,
Walker

**Comment by tarteo** [comment]
Related to: https://github.com/OCA/website/issues/587

**Comment by simahawk** [comment]
@walkerblackwell pls check if the solution described on #587 solves your issue.
Meanwhile we can close this as I don't see any further detail.
Feel free to reopen it if needed.
