### ISSUE TITLE
[STANDARD] website_menu_multilang: This module do not comply with standards 

### ISSUE THREAD

**Issue by nhomar** [OCA/website#65]
- [ ] README.rst
- [ ] Documentation
- [ ] Description

**Comment by pedrobaeza** [comment]
It was merged before these guidelines were set, and nobody has make a PR for enhancing it.

**Comment by nhomar** [comment]
Yes no problem, as you see I asigned to myself to take car of this Issue. It is just for My control and informing people.... I understand perfectly.
