### ISSUE TITLE
[12.0] [Website_cookie_notice] on click http 404 error URI (XHR)POST - https://****/website_cookie_notice/ok

### ISSUE THREAD

**Issue by PasLaurent** [OCA/website#659]
HTTP404: RESSOURCE MANQUANTE. Le serveur n’a trouvé aucune correspondance pour l’URI demandé (Uniform Resource Identifier).
(XHR)POST - https://*****/website_cookie_notice/ok

**Comment by pedrobaeza** [comment]
Please follow "Try me on runbot" badge on the README to try there if it's failing.
