### ISSUE TITLE
[12.0] [Website_cookie_notice] - wrong position in case enabling transparent block for Top Menu

### ISSUE THREAD

**Issue by kharkot** [OCA/website#664]
In case enabling transparent block for Top Menu additional class is added to header of homepage  :

class="homepage   o_header_overlay"

(duplicated on runbot)

![s1](https://user-images.githubusercontent.com/43400881/63760996-a9d38b00-c8c0-11e9-855e-945754fdeb04.jpg)
![s2](https://user-images.githubusercontent.com/43400881/63760997-aa6c2180-c8c0-11e9-99b8-23fc1bb2b409.jpg)

**Comment by pedrobaeza** [comment]
You are modifying HTML, so you must adapt accordingly cookie notice, but this is on your custom side, not on the module.

**Comment by kharkot** [comment]
@ pedrobaeza - I do not modify HTML directly - I have set only one option from website Builder (standard in Odoo)...
![s3](https://user-images.githubusercontent.com/43400881/63768384-5701cf80-c8d0-11e9-9ef0-70592a4af702.jpg)

But if that module is not universal - OK - your decision.

**Comment by pedrobaeza** [comment]
OK, you need to start from that then. Reopening.
