### ISSUE TITLE
How to add recaptcha into signup screen

### ISSUE THREAD

**Issue by tungpd0484** [OCA/website#675]
Hello 
I installed website_form_recaptcha and refer to website_crm_recaptcha in oder to add recaptcha into contactus by following code:

      <template id="contactus_form"
              inherit_id="website_crm.contactus_form"
              name="Contact Form Captcha">
        <xpath expr="//div[hasclass('form-field')][last()]" position="after">
            <div class="form-group row form-field o_website_form_required_custom">
                <label class="col-lg-3 col-md-4 col-form-label" for="g-recaptcha-response">Human?</label>
                <div class="col-lg-7 col-md-8">
                    <span class="o_website_form_recaptcha" required="" />
                </div>
            </div>
        </xpath>
      </template>

It will displayed recaptcha "I'm not a robot" checkbox.
But, similar it, I want to input above recaptcha into signup screen, then I add the following code:

    <template id="layout_signup_form" 
                      inherit_id="auth_signup.fields" 
                      name="Signup Field Customized">
         <xpath expr="//div[hasclass('field-confirm_password')]" position="after">
            <div class="form-group row form-field o_website_form_required_custom">
                <label class="col-lg-3 col-md-4 col-form-label" for="g-recaptcha-response">Human?</label>
                <div class="col-lg-7 col-md-8">
                    <span class="o_website_form_recaptcha" required="" />
                </div>
            </div>
        </xpath>
    </template>

It only displayed "Human?", haven't got "I'm not a robot" checkbox.
What should I do when add it into signup page?
Thank you very much in advance!

**Comment by citronpower** [comment]
Add the class "s_website_form" in your form.
```
<template id="signup_form" inherit_id="auth_signup.signup" name="Signup Form Captcha">
        <xpath expr="//form[hasclass('oe_signup_form')]" position="replace">
            <form class="oe_signup_form s_website_form" role="form" method="post" t-if="not message">
              <input type="hidden" name="csrf_token" t-att-value="request.csrf_token()"/>
                <t t-call="auth_signup.fields">
                    <t t-set="only_passwords" t-value="bool(token and not invalid_token)"/>
                </t>

                <p class="alert alert-danger" t-if="error">
                    <t t-esc="error"/>
                </p>
                <input type="hidden" name="redirect" t-att-value="redirect"/>
                <input type="hidden" name="token" t-att-value="token"/>
                <div class="form-group form-field o_website_form_required_custom">
                    <div class="col-md-7 col-sm-8">
                        <span class="o_website_form_recaptcha" />
                    </div>
                </div>
                <div class="clearfix oe_login_buttons">
                    <a t-attf-href="/web/login?{{ keep_query() }}" class="btn btn-link pull-right">Already have an account?</a>
                    <button type="submit" class="btn btn-primary pull-left o_signup_btn"> Sign up</button>
                </div>

            </form>
        </xpath>
    </template>
```

**Comment by tungpd0484** [comment]
Thank you so much for prompt reply, I can display in sign up form following your advice. I will close this issue here.
