### ISSUE TITLE
Recaptcha validation

### ISSUE THREAD

**Issue by joelperez96** [OCA/website#707]
Hi!
I've recently installed the website_form_recaptcha in my odoo community version 8 website. I follow the steps indicated in the description in order to set the recaptcha in the login form. I've established both site and secret key values in the system parameters, and I can see the recaptcha box in the login form. My issue is that I don't know how to make the validation in order to avoid the sucessful login if the recaptcha checkbox has not been checked. 
I guess I have to make some type of validation, either in the python code or setting up some type of configuration in my odoo website, but I don't know exactly what.
Can anyone help me?

Thank you!

**Comment by robertobarreiro** [comment]
Same issue here for v8.0 on contact form. Form validated and messages sended without captcha verification.

**Comment by joelperez96** [comment]
Hi Roberto! I finally solved the problem. What I've done is the following:
My problem was on the login form, so when I send the login form to the server, the method that validates this form is the method **_login** in **/usr/local/lib/python2.7/site-packages/openerp/addons/base/res/res_users.py**.
 In that method, the form fields (in this case username and password) are validated, so I have added a cheking also for the captcha field. 
So I added this lines at the beggining of the method:

def _login(self, db, login, password, **kwargs):
        if not password:
            return False
        user_id = False
        cr = self.pool.cursor() 

##ADDED THE FOLLOWING

        URIReCaptcha = 'https://www.google.com/recaptcha/api/siteverify'
        recaptchaResponse = request.params.get('g-recaptcha-response')
        private_recaptcha = '6LeedeQUAAAAAM3vVPEgZ7GGvVdo6dIta0BwxDMt' //Your private key
        ip_addr = request.httprequest.environ.get('HTTP_X_FORWARDED_FOR')
        if ip_addr:
            ip_addr = ip_addr.split(',')[0]
        else:
            ip_addr = request.httprequest.remote_addr
        params = urlencode({
            'secret': private_recaptcha,
            'response': recaptchaResponse,
            'remote_ip': ip_addr,
        })

        data = urlopen(URIReCaptcha, params.encode('utf-8')).read()
        result = json.loads(data)
        success = result.get('success', None)
        errorcodes = result.get('error-codes', None)
        #_logger.info("FYI err= "+str(errorcodes))
        if success == False and ("missing-input-response" in str(errorcodes)):
            return False

##THE REST OF THE METHOD AS ACTUALLY ...
        try:

Doing this, you are validating that recaptcha checkbox has been checked before validating the username and password.
Maybe in your case you are in another form and calling another python file, but you just should identify the python file and method that is validating the form, and add the cheking I've mentioned above.

Hope this was helpful for you!

**Comment by robertobarreiro** [comment]
Isn't that supposed to check on the form that has an object of class o_website_form_recaptcha, without having to add additional code?

**Comment by pedrobaeza** [comment]
No, it requires to be explicitly added.

**Comment by pedrobaeza** [comment]
Check website_crm_recaptcha for an example.

**Comment by joelperez96** [comment]
Hi Roberto! As Pedro said it requires to be added in the python code. In fact, the goal of a recaptcha is to avoid DoS or brute force attacks from bots. If you did the validation in the client side (it means, in the form), the bots would can skip these validation and send the requests to the server without problem. Due to it, the validation requires to be done in the server side, it means, in the python files, which will avoid the attack really.

**Comment by robertobarreiro** [comment]
Thank you Pedro and Joel. I will try to achieve it taking a look to website_crm_recaptcha. Have a nice day!
