### ISSUE TITLE
[10.0] website_multi_theme: Uninstallation removes automatic footer

### ISSUE THREAD

**Issue by HamaniKhalil** [OCA/website#717]
Hi, while trying to build a website I installed this module to see what features would I have in hand that may be useful. But at one point I realised that it didn't match my needs so I uninstalled it and that removed the website footer, alongside with the website editor switch "Automatic Footer" (in fact all the "Footer" section was removed from "Costumize" menu in the website editor)

I'd like to know if it's possible to get my automatic footer back. If so, then how ?

**Comment by pedrobaeza** [comment]
Which module? Which Odoo version?

**Comment by HamaniKhalil** [comment]
Oh sorry I didn't specify ! The module is website_multi_theme and I installed it on Odoo 10.0. In order to make sure that it was the one causing the trouble, I had do the following process :

    - Create a new database (or restore an existing one in which website builder is already installed)
    - Install website_multi_theme
    - Check the footer (ok at this point)
    - Uninstall website_multi_theme
    - Check the footer (encountered the problem)

**Comment by pedrobaeza** [comment]
Well, that module is very hacky and add/remove views that are attached to the theme, so it can be that you lose that them footer. If so, it's not possible to recover it.

**Comment by HamaniKhalil** [comment]
Yeah that's what I thought too ! But I needed to get community confirmation ! So thanks for the reply, and especially for being that quick! Have a good day.

**Comment by pedrobaeza** [comment]
OK, closing as "won't fix" due to the reasons above.
