### ISSUE TITLE
[12.0] website_lazy_load_image and events

### ISSUE THREAD

**Issue by baba75** [OCA/website#721]
Hello, 
when website_lazy_load_image is installed the Register button of an online Event is not working from mobile device.

**Comment by flotho** [comment]
Hi @baba75 , this need more informations and logs so that community could help.
JS messages in the console ? Sever messages ?

Regards

**Comment by baba75** [comment]
Hi @flotho , I do not know how to look at JS console on mobile; However, today I install an empty fresh DB with only events and website_lazy_load_image, and it worked. So it must be some other, maybe third-party modules that interfere. Thank you for your help, I will close the issue.

**Comment by flotho** [comment]
Is there any process payment in your workflow ?

**Comment by baba75** [comment]
Actually yes. In the past, I got a similar problem with payment as described here: https://github.com/OCA/website/issues/587
