### ISSUE TITLE
users can send messages in contact form without complete website_crm_recaptcha

### ISSUE THREAD

**Issue by robertobarreiro** [OCA/website#727]
I have installed website_crm_recaptcha at odoo8, I added google keys to my system parameters and captcha appears at my contact form, but send button can be clicked and message it's sended without making captcha verification.

The module install and use instructions are:

Configuration
Obtain ReCaptcha key from Google
Add site key to recaptcha.key.site system parameter
Add secret key to recaptcha.key.secret system parameter

Usage
To use this module, you need to:
Go to the Contact form on Website

Is there any other required step I haven't done?

Thanks in advice.

**Comment by ghost** [comment]
Same here (v13) .... Perhaps it is lack of experience on my part, but the instructions are not at all helpful.

- Already have a form-enabled model (refer to website_form docs)
- Set website_form_recaptcha to True on that model (similar to enabling forms)
- Add an element with the o_website_form_recaptcha class anywhere in the form

Maybe some more detailed instructions will help perhaps ?

**Comment by roberto-barreiro** [comment]
Adding an element o_website_form_recaptcha should be done installing the module website_form_recaptcha, and that module refers to website_crm_recaptcha as implementation example.

**Comment by pedrobaeza** [comment]
Yes, you need that extra step.

**Comment by roberto-barreiro** [comment]
I'm sorry Pedro, but that it's incorrect. Getting installed the both modules website_form_recaptcha and website_crm_recaptcha, adding an element with class "o_website_form_recaptcha" to the contact form, it's not only not necesary, but adding it, it shows 2 google captchas at contact form. I just have tested it.

**Comment by pedrobaeza** [comment]
Yes, I mean for other forms that are not that one.

**Comment by roberto-barreiro** [comment]
The question of this thread, it's about contact form and website_crm_captcha.

**Comment by pedrobaeza** [comment]
But both together are working correctly. You can check on runbot.

**Comment by roberto-barreiro** [comment]
Unable to test on runbot, because website_crm_recaptcha for odoo 8 was removed... It was available at the moment I opened this thread...

**Comment by pedrobaeza** [comment]
I can't say. V8 is so old...

**Comment by roberto-barreiro** [comment]
I can say I have downloaded it from odoo apps 19 days ago, not so old download. I can guess the reason for the recent removal of version 8.0. No problem, thanks for support.
