### ISSUE TITLE
[11.0][website_multi_theme] scss executable dependency in docker image

### ISSUE THREAD

**Issue by em230418** [OCA/website#734]
Hi!
As @Yajo pointed in https://github.com/OCA/website/issues/513 

> That's a dependency of odoo itself, not from this addon.

So I am using official docker image and there is no such dependency.

```
FROM odoo:11.0
USER root
RUN find / -name "scss"
```

**Comment by em230418** [comment]
So the question is, how to install it? https://www.npmjs.com/package/scss does not seem to be the right thing.

**Comment by yajo** [comment]
> So I am using official docker image and there is no such dependency.

Yes, that's why you should use another image :stuck_out_tongue_winking_eye: (\*ahem\* https://github.com/Tecnativa/doodba)

Go check https://sass-lang.com/install
