### ISSUE TITLE
Website_crm_recaptcha V13 sends contact-us form without requiring validated recaptcha's field

### ISSUE THREAD

**Issue by bakatasolutionssl** [OCA/website#744]
Hello,

We realized that when you send a message through contact-us's form , you can send it without check recaptcha's field added with Website_crm_recaptcha's module.

This issue is solved for Odoo 12 version but not for Odoo 13. 
Thank you.

Bakata Solutions Team

**Comment by lauramanteconbakata** [comment]
Dear team,

We just realize that Recaptcha works fine when the website's contact form is set to create an opportunity, but it does not work if the contact form is set to send an e-mail. How could we solve this ? Thank you!
