### ISSUE TITLE
key invalid - displayed in form

### ISSUE THREAD

**Issue by mqgdqlenq** [OCA/website#748]
Hi, 
we use both the recaptcha form and recaptcha crm, got the key and secret using V3 () and added the recaptcha in the contact form using the code as provided in the examples:

          <div class="form-group row form-field o_website_form_required_custom">
            <label class="col-lg-3 col-md-4 col-form-label o_fake_editable" for="g-recaptcha-response">Human?</label>
            <div class="col-lg-7 col-md-8">
              <span class="o_website_form_recaptcha" required="">
                <div class="g-recaptcha" data-sitekey="6LcfWcEZAAAAAHYCcNKODOr5JVnEvyxkBmdFcK-U">
                  <div style="width: 304px; height: 78px;">
                    <div>
                      <iframe src="https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcfWcEZAAAAAHYCcNKODOr5JVnEvyxkBmdFcK-U&amp;co=aHR0cHM6Ly9zbWF4dGVjLXRlc3QtMTM0MjI4NS5kZXYub2Rvby5jb206NDQz&amp;hl=de&amp;v=aUMtGvKgJZfNs4PdY842Qp03&amp;size=normal&amp;cb=jmuoe1pk0dx0" width="304" height="78" role="presentation" name="a-e3mbba21pn24" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"/>
                    </div>
                    <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"/>
                  </div>
                  <iframe style="display: none;"/>
                </div>
              </span>
            </div>
          </div>

on the website contact form is shows a error message.
Since the same error message is shown on the "try me" database that is linked to this module (http://3435596-12-0-782a45.runbot1-2.odoo-community.org/contactus) I assume it is a general bug and not faulty configuration. 

![image](https://user-images.githubusercontent.com/44089352/91039413-cfe35680-e60c-11ea-8d38-1a8d644b0aab.png)

**Comment by maxmenGMK** [comment]
I have the same error. The key is 100% valid because i tryed to use in another places and it works.
