### ISSUE TITLE
[13.0] website_crm_privacy_policy bug xpath

### ISSUE THREAD

**Issue by vanderperre** [OCA/website#803]
installation : XML parser don't find parent

suggestion

replace in templates/contactus.xml 

expr="//form/div/div/span[@id='o_website_form_result']/../.."
by
expr="//form//div/div/span[@id='o_website_form_result']/../.."

**Comment by wytzejan** [comment]
Please see my comment in OCA#804.
Your suggestion will also work but with a base website_form installation it's not really needed in my opinion.
