### ISSUE TITLE
[12.0] website_form_builder: Failing due to upstream changes

### ISSUE THREAD

**Issue by gustotc** [OCA/website#807]
Website_form module is undefined and dragging does not work, generating a log on the console.

Odoo 12 Community - updated on 01/12/2020

web_editor.assets_editor.js: 204 undefined have not insert action: data-drop-near or data-drop-in
start @ web_editor.assets_editor.js: 204

![Seleção_087](https://user-images.githubusercontent.com/7175315/100786582-1fe26e00-33f1-11eb-9901-dc632f125932.png)

**Comment by pedrobaeza** [comment]
This seems something of your deployment, as it's working properly on runbot. Please follow the "Try me on runbot" button on the README for trying.

**Comment by gustotc** [comment]
I created an installation from scratch, only with this module and crm and even then this error occurs.

Note: My version of Odoo is updated.

The console is reporting that the data drop is missing, do you have any idea about that?

**Comment by pedrobaeza** [comment]
I'm afraid not. Please try on runbot if you can reproduce the same problem.

**Comment by gustotc** [comment]
There is an alteration of the odoo that I suspect is what caused this module to stop.

Runbot does not really give an error, but at run time the problem I reported occurs.

![image](https://user-images.githubusercontent.com/7175315/100790048-0db6fe80-33f6-11eb-92d1-6401d70d0528.png)

**Comment by pedrobaeza** [comment]
But are you talking about a module in this repository?

**Comment by gustotc** [comment]
Odoo's own module, a change that modified the data-drop. It seems to me a very coincidence that the problem is occurring in exactly that.

**Comment by pedrobaeza** [comment]
But then you should put the issue in odoo/odoo, not here.

**Comment by pedrobaeza** [comment]
Or is the change in Odoo affecting a module of this repository?

**Comment by gustotc** [comment]
I'm trying to help, as an Odoo change may have modified a module for you, but it seems to me that you are not understanding.

OK.

**Comment by pedrobaeza** [comment]
No, I don't understand as you are not saying which module in this repository is affected. Are you talking about website_form_builder?

**Comment by gustotc** [comment]
Yes, because it creates a snippet in the web editor, and it is there that the problem is occurring that does not stop dragging and dropping to the form, even with everything configured.

**Comment by gustotc** [comment]
One question ... did the images I attached appear?

**Comment by pedrobaeza** [comment]
OK, now it seems more clear. Yes, images appear, but I'm not an expert of each OCA module, just an issue handler.

**Comment by gustotc** [comment]
got it, thanks Pedro.

I'm using this module and it seems to be very cool, but I came across this problem.

Refing to Odoo, I looked in the list of updates for something related to this to try to help identify the problem, because some changes they make can occur to affect extra modules.
