### ISSUE TITLE
the ReCaptcha module fail to install on Odoo 13 Enterprise

### ISSUE THREAD

**Issue by JJebara** [OCA/website#812]
It fails when looking for 2 fields 
1 error for 
Field `has_google_recaptcha` does not exist

Error while importing module 'website_form_recaptcha'.

 Error while validating view

Field `has_google_recaptcha` does not exist

Error context:
View `reCaptcha Settings`
[view_id: 4557, xml_id: n/a, model: res.config.settings, parent_id: 1832]
None
<odoo>
    <record id="view_website_config_settings" model="ir.ui.view">
        <field name="name">reCaptcha Settings</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="website.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <div id="google_maps_setting" position="after">
                <div class="col-xs-12 col-md-6 o_setting_box" id="reCaptcha_setting">
                    <div class="o_setting_left_pane">
                        <field name="has_google_recaptcha"/>
                    </div>
                    <div class="o_setting_right_pane">
                        <img width="20px" alt="captcha" class="mr-2" src="website_form_recaptcha/static/description/recaptcha_ico.png"/>
                        <label for="has_google_recaptcha" string="reCaptcha"/>
                        <span class="fa fa-lg fa-globe" title="Values set here are website-specific." groups="website.group_multi_website"/>
                        <div class="text-muted mt8">
                           Protect your forms using reCaptcha control.
                        </div>
                        <div class="content-group" attrs="{'invisible': [('has_google_recaptcha', '=', False)]}">
                            <div class="row mt16">
                                <label class="col-lg-5 o_light_label" for="recaptcha_key_site"/>
                                <field name="recaptcha_key_site" placeholder="XXXXX"/>
                                <label class="col-lg-5 o_light_label" for="recaptcha_key_secret"/>
                                <field name="recaptcha_key_secret" placeholder="XXXXX"/>
                            </div>
                        </div>
                        <div attrs="{'invisible': [('has_google_recaptcha', '=', False)]}" class="mt8">
                            <a role="button" class="btn-link" target="_blank" href="http://www.google.com/recaptcha/admin"><i class="fa fa-arrow-right"/>
                            How to get my reCaptcha Key
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </field>
    </record>
</odoo>
/tmp/tmpzp217h5v/website_form_recaptcha/views/website_config_settings.xml
7 
 Make sure those modules are installed and try again.

**Comment by pedrobaeza** [comment]
It seems you are trying to import the module. Can it be?

**Comment by JJebara** [comment]
Correct, I am trying to import the module, isn't that the manner to deploy it?

**Comment by pedrobaeza** [comment]
No, that's only for data module, which is nearly 0 of the existing modules. You need to put it on the addons path and refresh list.

**Comment by JJebara** [comment]
Thank you so much for helping on this. I figured it out. 
I may have missed the installation instructions .. I will double check. I added the modules to the add-on and was able to install. Have a wonderful day. Thank you :)

**Comment by pedrobaeza** [comment]
Sorry, but that's outside the scope of this issue, as it's very broad. Check Odoo documentation.
