### ISSUE TITLE
[12.0] website_no_crawler doesn't replace current robots.txt template

### ISSUE THREAD

**Issue by filipocc** [OCA/website#826]
Hi there,
i've just found an issue with website_no_crawler module.
I've checked the code, and it should replace all content inside <t> </t> label, but it is not working properly:
https://github.com/OCA/website/blob/d9ff29280ed14633d288c5d44ec57e50ffbe3983/website_no_crawler/views/disable_robots.xml#L4
![image](https://user-images.githubusercontent.com/15066476/109799042-ce2dc780-7c1b-11eb-8019-1f746be5b038.png)

Also, the new <t> content should have t-translation="off"

Why content is appearing twice in my robots.txt??

Thanks in advance!

**Comment by chienandalu** [comment]
The first issue is fixed here: https://github.com/OCA/website/pull/698/

The translation issue is fixed here: https://github.com/OCA/website/pull/831

**Comment by filipocc** [comment]
> The first issue is fixed here: #698
> 
> The translation issue is fixed here: #831

Thanks @chienandalu ! Closing this issue.
