### ISSUE TITLE
can you fix oca website scam links?

### ISSUE THREAD

**Issue by icf20** [OCA/website#858]
example

https://odoo-community.org/shop/product/location-management-aka-better-zip-652?search=base_location#attr=9121

```
<a target="_blank" href="http://www.camptocamp.com">
                                    <span class="website_detail">https://github.com/OCA/partner-contact</span>
                                </a>
```

**Comment by pedrobaeza** [comment]
Thanks for noticing. Fixed in https://github.com/OCA/apps-store/commit/05a1a41fb63b4adfd6cb030f269a4d81d972202f. Next time, you can take note of where to report the issue. Deployed manually in OCA instance.
