### ISSUE TITLE
RFC: optimize "Time to Interactive" and "Total blocking time"

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/website#887]
In the quest to improve the Web Core Vitals, I've managed to tame 4 out of 6, but the TTI and TBT are still an issue.

Even if CSS and JS are lazy-loaded, they are still quite bulky - besides the frontend assets also the common assets are included, which includes lumpy friends such as Bootstrap, jQuery UI, Underscore, ...

The problem is that processing their CSS and JS, especially on the "Mobile" simulation which assumes low network speed and a shitty phone CPU, leads to long tasks in downloading and processing the files, and then in case of CSS, re-rendering parts of the DOM because of it, and in case of JS, running it. I'm not 100% sure about the TBT definition but at least the TTI definition is totally in conflict with that, as it is a measure of "the moment when there has been at least X consecutive seconds without long tasks", where X is 5 or 10. The longer you delay the processing of your bulky files, the higher the TTI becomes. Unless you really delay it by 10-20 seconds, but then you are not presenting your user with a functional website eg. the dropdown menu is not functional.

I understand that some of the base Odoo CSS/JS cruft can not be done without, especially not on portal or webshop pages, but on the typical webpage that you are trying to optimize, some could surely be left out.

I have been thinking of several ways to go here:

1. On the properties page for each website, you are shown a list of which CSS and JS are part of the asset bundle, and you can then use checkboxes to disable some of those. To make this more userfriendly this could work with templates instead, so that you have a default, minimal template and some exception templates for otherwise dysfunctional pages. This would result in a number of separate asset bundles being generated, which are then being (lazy-)loaded on the pages that they adhere to. Result: less JS/CSS processing time, less long/blocking tasks, faster time to interactive.
2. Somehow cut up the available CSS/JS into smaller chunks, which are small enough so as not to be seen as a "long task". This would improve the TTI, not sure about the TBT. Also not sure how realistic this is.
3. Somehow instruct Odoo that certain CSS or JS should only be added when a certain widget is on the page. Odoo has a way of doing that, but for the main libraries this is not done. Maybe this mechanism could be stretched to also apply for the main libraries.

@tarteo What are your thoughts on this?

**Comment by tarteo** [comment]
@thomaspaulb I had somewhat the same idea a few months ago where can add a "selection" to a asset. Where it checks before hand the page if the snippet is present on the page something like:

```
<record id="snippet_css" model="ir.asset">
    <field name="bundle">web.assets_frontend</field>
    <field name="path">somestyle.scss</field>
    <field name="selection">section#mysnippet</field>
</record>
```
But that was all I didn't do anything with it. :smile:
