### ISSUE TITLE
please update website_snippet_barcode for Odoo14

### ISSUE THREAD

**Issue by berteh** [OCA/website#937]
**Is your feature request related to a problem?**
snippet_barcode is  a very useful feature to share short url to other medias (paper, smartphones)... and being able to include them as dynamic blocs in pages and report is great.

**Describe the solution you'd like**
update bloc code to be usable in v14

**Describe alternatives you've considered**
installing 3rd party software to generate QR code images.. but it's plain stupid when odoo is already working just fine.

**Comment by pedrobaeza** [comment]
You can fund the contributors of such module for doing the migration or migrate yourself. Please coordinate privately or on the general migration issue.
