### ISSUE TITLE
[14.0] [website_cookiefirst]

### ISSUE THREAD

**Issue by matteoopenf** [OCA/website#968]
## Module
[website_cookiefirst](https://github.com/OCA/website/tree/14.0/website_cookiefirst)
## Describe the bug
try to translate page and obtain :
load could not load template
ValueError: L'elemento '<xpath expr="//footer//div/span[hasclass('o_footer_copyright_name')]">' non può esser localizzato nella vista genitore

View name: footer_custom
Error context:

## To Reproduce
**Affected versions**:

- [ ] 14.0  https://github.com/OCA/website/pull/969
- [ ] 16 ?

1. install  module
2. configure module
3. try to translate website , and have the error

**Expected behavior**
it's possibile translate

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
https://github.com/odoo/odoo/blob/9cc56fc3d3cdb43e393df0975e10192c3b10f455/addons/website/views/website_templates.xml#L1351 in this view not exist this class o_footer_copyright_name so the xpath is not exact

**Comment by pedrobaeza** [comment]
Don't open an issue if you are going to open a PR.
