### ISSUE TITLE
[RFC] GDPR compliance: remove Google Fonts

### ISSUE THREAD

**Issue by PicchiSeba** [OCA/website#971]
**Is your feature request related to a problem?**
In order to have a GDPR compliant website we are aiming to reduce unnecessary calls to Google Fonts. That means self-hosting fonts instead of having them served by Google.

**Describe the solution you'd like**
Disable calls to `fonts.googleapis.com` when no fonts are being served from Google.
That also includes having the default fonts already self-hosted or making them self-hostable (I tried to add them again and disabling the `Serve font from Google servers` flag but it doesn't work).

**Describe alternatives you've considered**

**Additional context**

EDIT: improved readability

**Comment by pedrobaeza** [comment]
AFAIK this is already done by Odoo itself. Anyway, do you plan to do any additional module in this repo?

**Comment by PicchiSeba** [comment]
I checked with a small local test and saw that `fonts.googleapis.com` was still being called (it seems that Roboto is served through Google and I can't figure how to set it to be hosted locally).
That's when i opened this issue. Maybe I'm doing something wrong?

Anyway if turns out that it wasn't a mistake on my part we could consider adding a module to fix it.

**Comment by pedrobaeza** [comment]
Well, you should open then the issue in odoo/odoo, not here.

**Comment by PicchiSeba** [comment]
Ok, closing here. Sorry for the trouble
