### ISSUE TITLE
UncaughtClientError > TypeError  in Contact Form after install and configuration website_google_tag_manager

### ISSUE THREAD

**Issue by alvarojimenezpaz** [OCA/website#976]
UncaughtClientError > TypeError
Unknown javascript error > Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
    at HTMLDocument.<anonymous> (<anonymous>:1:199)

## Module
website_google_tag_manager

## Describe the bug
When clicking on Send in the Contact Form, it gives an error but there are no errors in the log:
"UncaughtClientError > TypeError
Unknown javascript error > Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
    at HTMLDocument.<anonymous> (<anonymous>:1:199)"
    

## To Reproduce
odoo 16

1. https://edificioplazamayor.cl/es_CL/contactus
2. clink on SEND
3.
![image](https://user-images.githubusercontent.com/37876624/235817996-cd8dcbc7-a97b-4ed1-84df-7110977e0d1e.png)

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem on runboat (clicking on the button "Runbot | Try me" of the module).
