### ISSUE TITLE
[8.0] website_sale_vat_required - Doesn't show field VAT in checkout & README

### ISSUE THREAD

**Issue by rafaelbn** [OCA/website#98]
After testing in runbot, with this module installed you cannot buy because when you and in the checkout form you cannot confirm the order. I guess when I click in "confirm" button Odoo ask for VAT because is required but as this field is not shown you cannot fill it.

After this test and issue I discover that README of this module is not up-to-date, there is not runbot button and there is not bug tracker link

**Comment by rafaelbn** [comment]
From:
- https://github.com/OCA/e-commerce/pull/43 (correct branch - closed)
- https://github.com/OCA/website/pull/24/ (merged)

cc @pedrobaeza @Yajo @sergio-incaser @carlos-incaser @eLBati @LeartS

**Comment by eLBati** [comment]
@rafaelbn just tested on http://3118880-8-0-0c5e0b.runbot2.odoo-community.org (base DB)
- installed module website_sale_vat_required
- went to http://3118880-8-0-0c5e0b.runbot2.odoo-community.org/shop/checkout (both with logged and anonymous user)

I can see 'VAT Number' field.

Could you describe the steps to reproduce the problem?

Thanks

**Comment by rafaelbn** [comment]
Solved not sure where...
