### ISSUE TITLE
GDPR Europe Sign-Up Double-Opt

### ISSUE THREAD

**Issue by KaiBoos** [OCA/website#980]
In Europe there was a ruling. A client signed up on a website and entered a wrong mail.
The reciever of the mail went to court against the website-provider and was Right.
Even on Account-Signups a double-opt-in is required. Actually everytime before a mail is sent it need to double opt-out.

Can you double-opt-in on account signup?

Thanks for the help!
Kai

**Comment by pedrobaeza** [comment]
Can you please attach the corresponding parts of the law that says that it should be that way?

**Comment by NICO-SOLUTIONS** [comment]
Would be interested in the mentioned case. 
As far as I know the double opt in is not more GDPR complaint then the single opt in... in terms of legal view... 
it is more or less a "best practice" to implement it.

But if you have any further informations on this... please share.

**Comment by KaiBoos** [comment]
Here is the german source.
But I think anyone can use Google-translate.


https://www.e-recht24.de/news/ecommerce/8214-achtung-abmahnung-gericht-untersagt-anmeldebestaetigung-fuer-shops.html

**Comment by NICO-SOLUTIONS** [comment]
Thanks... 
ok i need to dig a bit further... 
but for now it looks like, that it is not very clear if you overcome this problem with double opt... the first mail with informations about the request of account creation providing a link to perform the account creation it self can be declared as spam (or promotional) as well...  
will have a deeper look into it.

**Comment by KaiBoos** [comment]
So the same source suggests:

The following text as opt-in would be possible:

"You have been registered to the shop XYZ.
Please confirm that it was you by pressing this link (or entering this code on login).

If you do not activate the link you will not receive any more messages from us.
Your mailadress will be removed automatically."

This mail is not allowed to have any kind of commercial.

And the process needs to be fully documented/archived (as stated in another verdict)

So I am thinking on using an addon and changing the mail accordingly. Will do some more research.

**Comment by KaiBoos** [comment]
My actual problem was, that someone can just order my shop-product (event) without registration. 
Then this leads to an mail which has not been opt --> bad.

So I make registration mandatory --> double opt --> buy product.

Damn I love GDPR/DSGVO ...

**Comment by NICO-SOLUTIONS** [comment]
Just in general...
If you make the registration mandatory. As soon as you register your account, it will send a mail for the creation of your account. 
So how to make sure, that this acount was not created by anyone else? So i dont think that you will bypass the mentioned problem this way... 

Yeah DSGVO can be quite exhausting on one hand...
