### ISSUE TITLE
[14.0][website_cookiefirst] not work on odoo.sh

### ISSUE THREAD

**Issue by matteoopenf** [OCA/website#995]
## Module
website_cookiefirst

## Describe the bug
Actually in one istance of odoo.sh with multisite the module not work and block add product cart, block reset password and other operation

## To Reproduce
**Affected versions**:

- [ ] 14.0

1. Install the module in multi site istance
2. put the key in configuration
3.  after that we have a block on the shop to add product on the cart, reset password and other operation

**Expected behavior**
The module work fine

**Additional context**

I think the problem is odoo.sh, but I don't exact which is the problem because actually we have another istance withoutt problem, but it's a single site istance.

**Comment by pedrobaeza** [comment]
It seems CookieFirst is having some troubles lately, or the module should be adapted, but nothing to do with Odoo.sh. It's general.

**Comment by matteoopenf** [comment]
> It seems CookieFirst is having some troubles lately

thank you

The strange thing is that in one instance it works and in one it doesn't.
The only difference is that one is multi-site
I have now also opened a ticket to cookiefirst.

**Comment by matteoopenf** [comment]
Now works again
